services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Keerthi@123
      MYSQL_DATABASE: smart_agri
      MYSQL_USER: Keerthana
      MYSQL_PASSWORD: Keerthi@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:7
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Keerthana
      MONGO_INITDB_ROOT_PASSWORD: Keerthi@123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data: