import { createContext, useContext, useState, useEffect, useCallback, useMemo } from "react";

export const AppContext = createContext();
export const useApp = () => {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error("useApp must be used within AppProvider");
  return ctx;
};

/* ─────────────────────────────────────────────
   TRANSLATION TABLE  (en / ta / hi)
───────────────────────────────────────────── */
const T = {

/* ════════════════════════════════════════════
   ENGLISH
════════════════════════════════════════════ */
en: {
  /* nav */
  home:"Home", dashboard:"Dashboard", farmMgmt:"Farm Management",
  sensors:"Sensor Monitor", crops:"Crop Advice", irrigation:"Irrigation",
  soil:"Soil Analysis", weather:"Weather", reports:"Reports",
  profile:"Profile", history:"Farm History", logout:"Logout",
  /* auth */
  welcomeBack:"Welcome back", signIn:"Sign in to your AgroSmart account",
  username:"Username", password:"Password",
  farmer:"Farmer", signInBtn:"Sign In", newFarmer:"New farmer?",
  createAcc:"Create free account", orGuest:"or continue as",
  guestMode:"Guest (Browse Only)", fillAll:"Please fill in all fields.",
  createAccount:"Create Account", registerSub:"Register your farm to get started",
  fullName:"Full Name", mobile:"Mobile Number", village:"Village / Town",
  state:"State", farmSize:"Farm Size (Acres)", primaryCrop:"Primary Crop",
  confirmPwd:"Confirm Password", alreadyHave:"Already have an account?",
  passwordsMustMatch:"Passwords do not match.", minChars:"Min 6 chars",
  farmSizePlaceholder:"e.g. 10",
  authStatFree:"Free", authStatForever:"Forever",
  authStatSetup:"5min", authStatSetupLabel:"Setup",
  authStat247:"24/7", authStatMonitoring:"Monitoring",
  /* home hero */
  heroTag:"🌱 Smart Farming for Modern India",
  heroTitle:"Monitor Your Farm", heroAccent:"From Anywhere",
  heroSub:"Real-time soil, weather, and crop data at your fingertips.",
  goToDash:"Go to Dashboard", registerFree:"Register Free",
  featuresTitle:"Everything Your Farm Needs",
  featuresSub:"A complete agriculture monitoring platform built with farmers in mind.",
  aboutBadge:"About the Project", aboutTitle:"Built for India's Farmers",
  getStarted:"Get Started Free",
  ctaTitle:"Ready to Transform Your Farm?",
  ctaSub:"Join thousands of farmers already using AgroSmart to grow smarter.",
  featuresLink:"Features", aboutLink:"About",
  farmersLabel:"Farmers", uptimeLabel:"Uptime",
  waterSavedLabel:"Water Saved", yieldBoostLabel:"Yield Boost",
  featureRtSensors:"Real-time Sensors",
  featureRtSensorsDesc:"Monitor soil moisture, temperature, pH, and humidity instantly.",
  featureWeather:"Weather Intelligence",
  featureWeatherDesc:"Get hyperlocal weather forecasts and smart irrigation alerts.",
  featureIrrigation:"Smart Irrigation",
  featureIrrigationDesc:"Automate watering schedules based on soil moisture data.",
  featureCrops:"Crop Recommendations",
  featureCropsDesc:"AI-powered crop suggestions tailored to your soil profile.",
  featureSoil:"Soil Health Analysis",
  featureSoilDesc:"Track NPK levels, pH balance, and organic matter year-round.",
  featureAnalytics:"Analytics & Reports",
  featureAnalyticsDesc:"Detailed seasonal reports, yield predictions, and trend charts.",
  benefitNoTech:"No technical expertise needed",
  benefitMobile:"Works on phone, tablet, desktop",
  benefitLang:"Tamil, Hindi & English support",
  benefitAlerts:"Real-time alerts and notifications",
  benefitFree:"Free for small farm owners",
  benefitResearch:"Backed by agricultural research data",
  aboutDesc:"AgroSmart is a modern monitoring platform for Indian farmers.",
  footerTagline:"Smart Agriculture Monitoring System",
  footerCopyright:"© 2026 | Capstone Project | React PWA",
  smartAgriPlatform:"Smart Agriculture Platform",
  liveDashboard:"Live Dashboard",
  /* dashboard */
  goodMorning:"Good Morning", goodAfternoon:"Good Afternoon", goodEvening:"Good Evening",
  allSensorsActive:"Here's your farm overview. All sensors are active.",
  temperature:"Temperature", humidity:"Humidity", soilMoisture:"Soil Moisture",
  phLevel:"pH Level", weeklyTrends:"Weekly Sensor Trends",
  recentActivity:"Recent Activity", quickAccess:"Quick Access",
  optimalRange:"Optimal range for crops", goodMoisture:"Good moisture in air",
  wellIrrigated:"Well irrigated", neutralIdeal:"Neutral — ideal",
  alertLowBatteryTitle:"Low Battery — Sensor Alert",
  alertLowBatteryMsg:"Humidity Sensor (Field D) at 23% battery. Replace soon to avoid data loss.",
  alertRainTitle:"Rain Forecast — Irrigation Advisory",
  alertRainMsg:"Heavy rain expected Wednesday. Consider pausing irrigation for Field C.",
  actIrrigation:"Irrigation started for Field A",
  actLowBattery:"Low battery on Humidity Sensor (Field D)",
  actHarvest:"Crop harvest scheduled for Field B (Rice)",
  actPhReading:"New acidity reading recorded: 6.8 (Optimal)",
  actRainForecast:"Rain forecast for next 3 days",
  actFertilizer:"NPK fertilizer applied to Wheat field",
  /* farm */
  farmMgmtTitle:"Farm Management", farmMgmtSub:"Manage your farm details and monitor all fields",
  farmDetails:"Farm Details", farmName:"Farm Name", owner:"Owner",
  location:"Location", totalArea:"Total Area", established:"Established",
  soilTypeLabel:"Soil Type", waterSource:"Water Source", activeCrops:"Active Crops",
  totalFields:"Total Fields", irrigated:"Irrigated", healthyFields:"Healthy Fields",
  needAttention:"Need Attention", cropCalendar:"Crop Calendar", fieldOverview:"Field Overview",
  health:"Health", noIrrigation:"No Irrigation",
  farmLocation:"Coimbatore, Tamil Nadu",
  borewellLabel:"Borewell", canalLabel:"Canal",
  /* field / crop keys */
  fieldA:"Field A", fieldB:"Field B", fieldC:"Field C", fieldD:"Field D",
  allFields:"All Fields",
  cropRice:"Rice", cropWheat:"Wheat", cropSugarcane:"Sugarcane", cropCotton:"Cotton",
  cropMaize:"Maize", cropSoybean:"Soybean", cropPulses:"Pulses", cropVegetables:"Vegetables",
  areaAcre:"Acres", seasonKharif:"Kharif", seasonRabi:"Rabi", seasonAnnual:"Annual",
  irrDrip:"Drip", irrSprinkler:"Sprinkler", irrFurrow:"Furrow",
  /* calendar */
  mJun:"Jun", mJul:"Jul", mAug:"Aug", mSep:"Sep", mOct:"Oct", mApr:"April", mMay:"May",
  calTask1:"Sowing — Rice (Field A)", calTask2:"Fertilizer — Wheat (Field B)",
  calTask3:"Irrigation Schedule — Field C", calTask4:"Pesticide — Cotton (Field D)",
  calTask5:"Harvest — Rice (Field A)",
  done:"Done", pending:"Pending",
  /* sensors */
  sensorMonitor:"Sensor Monitoring", sensorSub:"Live data from IoT sensors across your fields",
  totalSensors:"Total Sensors", active:"Active", warning:"Warning", offline:"Offline",
  refreshData:"Refresh Data", refreshing:"Refreshing...", allSensors:"All Sensors",
  sensorDataLog:"Sensor Data Log", sensorId:"Sensor ID", name:"Name", type:"Type",
  currentValue:"Current Value", battery:"Battery", status:"Status", lastUpdate:"Last Update",
  lowBattery:"Low battery — replace soon",
  lastRefreshed:"Last:", sensorStatusActive:"active",
  sensorStatusWarning:"warning", sensorStatusInactive:"inactive",
  sensorFieldA:"Field A - Soil Sensor", sensorFieldB:"Field B - Temp Sensor",
  sensorFieldC:"Field C - pH Sensor", sensorFieldD:"Field D - Humidity",
  sensorGreenhouse:"Greenhouse - CO₂", sensorFieldE:"Field E - Wind",
  su2min:"2 min ago", su1min:"1 min ago", su5min:"5 min ago",
  su3min:"3 min ago", su4min:"4 min ago", su2hrs:"2 hrs ago",
  /* crops */
  cropAdvice:"Crop Recommendations", cropSub:"AI-powered suggestions based on your soil and climate data",
  whyCrop:"Why this crop?", recFertilizer:"Recommended Fertilizer (kg/ha)",
  duration:"Duration", waterNeed:"Water Need", expectedYield:"Expected Yield",
  season:"Season", soilSummary:"Soil Analysis Summary",
  overallScore:"Overall Soil Score", match:"Match",
  overallScoreNote:"Your soil is in good condition. Minor improvements can boost yield.",
  downloadSoilReport:"Download Soil Report",
  neutral:"Neutral — Optimal", adequate:"Adequate", slightlyHigh:"Slightly High",
  good:"Good", optimalRng:"Optimal Range",
  dur120_150:"120-150 days", dur10_12m:"10-12 months", dur180_200:"180-200 days",
  waterHigh:"High", waterMedium:"Medium",
  reasonRice:"Optimal soil pH (6.8), high moisture (74%), temperature (30-34°C) — ideal for rice.",
  reasonSugarcane:"Well-draining loam with adequate potassium and warm climate supports sugarcane.",
  reasonCotton:"Red loam soil with moderate nitrogen and adequate sunlight matches cotton.",
  yield45:"4.5 T/Acre", yield35:"35 T/Acre", yield18:"1.8 T/Acre",
  stageFlowering:"Flowering", stageGermination:"Germination",
  stageMaturation:"Maturation", stageBollFormation:"Boll Formation",
  soilScore:"82/100",
  /* irrigation */
  irrigationMgmt:"Irrigation Management", irrigationSub:"Control and monitor your irrigation systems in real time",
  waterToday:"Water Used Today", thisWeek:"This Week", efficiency:"Efficiency",
  nextScheduled:"Next Scheduled", motorControl:"Motor Control",
  mainPumpMotor:"Main Pump Motor", running:"Running", stopped:"Stopped",
  pumpOffline:"Pump is offline", startMotor:"Start Motor", stopMotor:"Stop Motor",
  fieldStatus:"Field Status", irrigAlerts:"Irrigation Alerts",
  startTime:"Start Time", endTime:"End Time", schedule:"Schedule",
  waterReq:"Water Required", scheduleIrrigation:"Schedule Irrigation",
  flow:"Flow", dripIrrigation:"Drip Irrigation",
  motorRuntime:"Motor Runtime", powerConsumption:"Power Consumption",
  motorRuntimeVal:"4h 20min", powerConsumptionVal:"2.4 kWh",
  fieldStatus_irrigating:"Irrigating", fieldStatus_scheduled:"Scheduled",
  fieldStatus_completed:"Completed", fieldStatus_off:"Off",
  tomorrowAM:"Tomorrow 6 AM",
  irrDur1:"2 hrs remaining", irrDur2:"Tomorrow 6 AM", irrDur3:"Completed at 10 AM",
  irrFlow:"45 L/min",
  irrAlert1:"Field D soil moisture critically low (42%). Immediate irrigation recommended.",
  irrAlert2:"Rain expected in 2 days. Consider reducing irrigation for Field C.",
  irrAlert3:"Field A irrigation efficiency at 91% — optimal performance.",
  swrSandyLoam:"Drains fast — irrigate frequently in short bursts.",
  swrClayLoam:"Retains water well — avoid over-irrigation.",
  swrSiltLoam:"Balanced drainage — standard schedule works.",
  swrRedLoam:"Moderate drainage — monitor moisture closely.",
  swrBlackCotton:"High water retention — reduce frequency.",
  swrUnit:"L/acre/hr",
  /* soil */
  soilAnalysis:"Soil Analysis", soilSub:"Monitor soil health parameters across your fields",
  nitrogen:"Nitrogen (N)", phosphorus:"Phosphorus (P)", potassium:"Potassium (K)",
  phLevelLabel:"pH Level", organicMatter:"Organic Matter",
  soilTemp:"Temperature", moisture:"Moisture", ideal:"Ideal",
  phSimulator:"pH Level Simulator", soilNutrient:"Soil Nutrient Profile",
  soilType:"Soil Type", waterNeeded:"Water Needed", waterSchedule:"Irrigation Schedule",
  bestCrops:"Best Crops", drainage:"Drainage",
  veryAcidic:"Very Acidic", slightlyAcidic:"Slightly Acidic",
  neutralIdealPh:"Neutral — Ideal", slightlyAlkaline:"Slightly Alkaline",
  veryAlkaline:"Very Alkaline",
  addLimeTip:"Add lime to raise pH", teaBerryTip:"Suitable for tea, berries",
  optimalCropTip:"Optimal for most crops", addSulfurTip:"Add sulfur to lower pH",
  poorNutrientTip:"Poor nutrient availability",
  lowOrganicTitle:"Low Organic Matter in Field D",
  lowOrganicMsg:"Organic matter at 1.8% — below ideal range. Consider adding compost before next season.",
  soilDrainage:"Drainage", bestCropsLabel:"Best Crops",
  currentSoilLabel:"Current Soil", idealLabel:"Ideal",
  requiredLabel:"Required", basedOnLabel:"based on",
  soilSandyLoam:"Sandy Loam", soilClayLoam:"Clay Loam", soilSiltLoam:"Silt Loam",
  soilRedLoam:"Red Loam", soilBlackCotton:"Black Cotton",
  scSandyLoam:"Rice, Groundnut, Vegetables", scClayLoam:"Cotton, Sugarcane, Soybean",
  scSiltLoam:"Wheat, Maize, Sunflower", scRedLoam:"Cotton, Groundnut, Pulses",
  scBlackCotton:"Cotton, Sorghum, Chickpea",
  spSandyLoam:"Drains quickly — irrigate frequently. Low nutrient retention; add compost.",
  spClayLoam:"Retains water and nutrients well. Prone to waterlogging — ensure good drainage.",
  spSiltLoam:"Balanced drainage. Excellent for most crops with standard irrigation.",
  spRedLoam:"Good iron content. Moderate water needs. pH ideal for most cash crops.",
  spBlackCotton:"Very high water retention. Reduce irrigation frequency significantly.",
  drainFast:"Fast", drainSlow:"Slow", drainModerate:"Moderate", drainVerySlow:"Very Slow",
  /* weather */
  weatherOverview:"Weather Overview", weatherSub:"Hyperlocal forecast for your farm location",
  dayForecast:"7-Day Forecast", farmImpact:"Farm Impact Analysis",
  recommendations:"Recommendations", farmNews:"Farm News",
  partlyCloudy:"Partly Cloudy", humidity_lbl:"Humidity", wind:"Wind",
  rainfall:"Rainfall", uvIndex:"UV Index", visibility:"Visibility", pressure:"Pressure",
  today:"Today", tomorrow:"Tomorrow",
  riceImpact:"Beneficial — rain will reduce irrigation need",
  wheatImpact:"Caution — excess moisture may cause fungal issues",
  sugarcaneImpact:"Optimal — warm weather supports growth",
  cottonImpact:"Monitor — heavy rain may damage open bolls",
  tip1:"Pause irrigation for Field A & C — rain forecast for next 2 days",
  tip2:"Apply fungicide to Wheat crop before expected rain on Wednesday",
  tip3:"Harvest-ready Cotton in Field D should be picked before Thursday rain",
  tip4:"Check drainage in low-lying fields to prevent waterlogging",
  weatherSunny:"Sunny", weatherClearSky:"Clear Sky", weatherUvHigh:"(High)",
  impactRiceCrop:"Rice (Field A)", impactWheatCrop:"Wheat (Field B)",
  impactSugarCrop:"Sugarcane (Field C)", impactCottonCrop:"Cotton (Field D)",
  weatherHumidity:"68%", weatherWindSpeed:"14 km/h",
  weatherRainfall:"12 mm", weatherUvValue:"6",
  weatherVisibility:"8 km", weatherPressure:"1012 hPa", weatherTemp:"33°C",
  /* reports */
  reportsAnalytics:"Reports & Analytics", reportsSub:"Comprehensive insights and performance data",
  totalWater:"Total Water Used", avgSoil:"Avg Soil Health", cropYield:"Crop Yield",
  activeAlerts:"Active Alerts", monthSummary:"Monthly Summary",
  exportPDF:"Export Full Report (PDF)", downloadCSV:"Download CSV",
  month:"Month", water:"Water", temp:"Temp", yield:"Yield",
  rainfallVsTemp:"Rainfall vs Temperature (Annual)",
  monthlyCropYield:"Monthly Crop Yield", waterSourceDist:"Water Source Distribution",
  soilCol:"Soil", rainfallMm:"Rainfall (mm)", avgTempC:"Avg Temp (°C)", cropYieldPct:"Crop Yield (%)",
  dripIrrigationLabel:"Drip Irrigation", rainwaterLabel:"Rainwater",
  rptPdfTitle:"AgroSmart Farm Report", rptGenerated:"Generated:",
  rptPdfFooter:"Generated by AgroSmart - Smart Agriculture Monitoring System",
  rptPdfFilename:"AgroSmart_Report.txt", rptCsvFilename:"AgroSmart_Summary.csv",
  rptTotalWater:"Total Water Used", rptWaterVal:"28,450 L",
  rptAvgSoil:"Avg Soil Health", rptSoilVal:"80%",
  rptCropYield:"Crop Yield", rptYieldVal:"4.2 T/Acre", rptActiveAlerts:"Active Alerts",
  reportWaterUnit:"L", reportTempUnit:"°C", reportYieldUnit:"T/Ac",
  /* units */
  unitKmh:"km/h", unitMm:"mm", unitC:"°C",
  unitL:"L", unitKg:"kg", unitMg:"mg", unitG:"g",
  unitKgHa:"kg/ha", unitMgKg:"mg/kg", unitPpm:"ppm",
  unitTAc:"T/Ac", unitKwh:"kWh", unitHpa:"hPa",
  unitPercent:"%", unitAcre:"Acres", unitLMin:"L/min", unitLAcHr:"L/acre/hr",
  unitKg_s:"kg", unitLitres:"litres", unitBags:"bags", unitGrams:"grams", unitMl:"ml",
  timeAM:"AM", timePM:"PM",
  minAgo:"min ago", hrAgo:"hr ago", hrsAgo:"hrs ago",
  /* farm history */
  farmHistory:"Farm History", historySub:"Track all farm activities and inputs week by week",
  addActivity:"Add Activity", activityType:"Activity Type", quantity:"Quantity",
  notes:"Notes", date:"Date", noHistory:"No history yet. Start recording farm activities.",
  field:"Field", unit:"Unit", aiSuggestion:"AI Suggestion", weekOf:"Week of",
  fieldLabel:"Field", all:"All", optionalNotes:"Optional notes",
  aiSuggestionPrefix:"AI Suggestion:",
  lastUsedMsg:"Last used", considerSimilar:"Consider similar quantity this week.",
  histPlaceholder:"e.g. 25",
  act_urea:"Urea Application", act_pesticide:"Pesticide Spray",
  act_npk:"Fertilizer (NPK)", act_dap:"DAP Application",
  act_potash:"Potash Application", act_organic:"Organic Manure",
  act_irrigation:"Irrigation", act_soilTest:"Soil Testing",
  act_harvest:"Harvesting", act_sowing:"Sowing / Planting",
  act_weeding:"Weeding", act_fungicide:"Fungicide Spray", act_other:"Other",
  /* profile / settings */
  myProfile:"My Profile", editProfile:"Edit Profile", saveProfile:"Save Profile",
  deleteAccount:"Delete Account", confirmDelete:"Are you sure you want to delete your account?",
  profileUpdated:"Profile updated successfully!", settings:"Settings",
  dangerZone:"Danger Zone", dangerNote:"Deleting your account will permanently remove all your data.",
  settingsTitle:"Settings", darkMode:"Dark Mode", lightMode:"Light Mode",
  toggleTheme:"Toggle app theme", languageLabel:"Language",
  languageSub:"Select your preferred language",
  guestBrowsingMsg:"You are browsing in guest mode. Register to save your farm data.",
  yesDelete:"Yes, Delete",
  /* notifications */
  notifications:"Notifications", markAllRead:"Mark all read", noNotifications:"No new notifications",
  /* common */
  save:"Save", cancel:"Cancel", edit:"Edit", delete:"Delete", update:"Update",
  search:"Search", filter:"Filter", export:"Export", download:"Download",
  selectState:"Select state", selectCrop:"Select crop", liveMode:"Live",
  /* fertilizer */
  fertilizerRec:"Fertilizer Recommendation",
  fertilizerSub:"AI-powered fertilizer suggestions based on crop type and soil data",
  selectCropLabel:"Select Crop", recommendationLabel:"Recommendation",
  pleaseSelectCrop:"Please select a crop to see recommendation",
  npkFertilizer:"NPK Fertilizer", ureaFertilizer:"Urea",
  dapFertilizer:"DAP", potashFertilizer:"Potash",
  fertilizerDetails:"Fertilizer Details", applicationRate:"Application Rate",
  applicationTime:"Application Time", benefits:"Benefits",
  precautions:"Precautions", mixingInstructions:"Mixing Instructions",
  fertRateRice:"90-60-40 kg/ha", fertTimeRice:"Basal + tillering",
  fertBenRice:"Boosts tillering and grain fill",
  fertPrecRice:"Split apply N — do not apply all at once", fertMixRice:"Broadcast before transplanting",
  fertRateWheat:"60-30-30 kg/ha", fertTimeWheat:"Sowing + 21 days",
  fertBenWheat:"Strong root development",
  fertPrecWheat:"Avoid waterlogging after DAP", fertMixWheat:"Mix with dry soil before drilling",
  fertRateCotton:"60-30-60 kg/ha", fertTimeCotton:"45 & 75 days",
  fertBenCotton:"Boll setting, fiber quality",
  fertPrecCotton:"Do not over-apply — causes leaf burn", fertMixCotton:"Dissolve in water for drip",
  fertRateSugarcane:"120-60-120 kg/ha", fertTimeSugarcane:"Planting + ratoon",
  fertBenSugarcane:"Fast vegetative growth",
  fertPrecSugarcane:"Apply in splits — 3 doses", fertMixSugarcane:"Broadcast near root zone",
  /* admin */
  adminPanel:"Admin Panel", systemHealthy:"System Healthy",
  uptimeMonth:"uptime this month", systemOpsMsg:"System status: All systems operational.",
  registeredFarmers:"Registered Farmers", goToFarmerDash:"Go to Farmer Dashboard",
  nameCol:"Name", villageCol:"Village", cropCol:"Crop", areaCol:"Area", statusCol:"Status",
  farmerActive:"active", farmerInactive:"inactive",
  adminFarmer1Name:"Rajesh Kumar", adminFarmer1Village:"Pollachi",
  adminFarmer2Name:"Priya Devi", adminFarmer2Village:"Erode",
  adminFarmer3Name:"Suresh Babu", adminFarmer3Village:"Salem",
  adminFarmer4Name:"Kavitha M.", adminFarmer4Village:"Madurai",
  /* news */
  newsNotFound:"Article not found", newsGoBack:"Go Back", newsBack:"Back",
  newsTodayFarmNews:"Today's Farm News",
  newsReadTime3:"3 min read", newsReadTime4:"4 min read", newsReadTime5:"5 min read",
  newsAlertTitle:"Understanding Sensor Battery Life & Maintenance",
  newsAlertCategory:"Sensor Maintenance",
  newsAlertB1:"IoT soil sensors typically last 6-12 months on a single charge. Low battery can cause inaccurate readings.",
  newsAlertB2:"Best practices:", newsAlertB3:"• Check battery levels weekly",
  newsAlertB4:"• Replace when battery drops below 25%", newsAlertB5:"• Clean sensor probes monthly",
  newsAlertB6:"• Avoid direct sunlight", newsAlertB7:"• Store spare batteries in cool, dry location",
  newsAlertB8:"Humidity sensors are especially sensitive — low battery can cause 15% drift in readings.",
  newsWeatherTitle:"How to Prepare Your Farm for Heavy Rain", newsWeatherCategory:"Weather Advisory",
  newsWeatherB1:"Heavy rainfall can cause waterlogging and crop damage if farms are not prepared.",
  newsWeatherB2:"Drainage:", newsWeatherB3:"• Clear all drainage channels before rain",
  newsWeatherB4:"• Ensure bunds are intact", newsWeatherB5:"• Install pumps in low-lying areas",
  newsWeatherB6:"Crop protection:", newsWeatherB7:"• Avoid fertilizers 48 hours before rain",
  newsWeatherB8:"• Stake tall crops to prevent lodging", newsWeatherB9:"• Harvest mature crops before heavy rain",
  newsWeatherB10:"Irrigation:", newsWeatherB11:"• Stop irrigation 24-48 hours before rain",
  newsWeatherB12:"• Check pumps after rain", newsWeatherB13:"Post-rain:",
  newsWeatherB14:"• Test soil pH after heavy rain — it often drops",
  newsWeatherB15:"• Monitor for fungal diseases in humid conditions",
  newsCropTitle:"Rice Harvest: Signs of Readiness & Best Practices", newsCropCategory:"Crop Management",
  newsCropB1:"Knowing the right time to harvest maximizes grain quality and yield.",
  newsCropB2:"Signs rice is ready:", newsCropB3:"• 80-85% of grains turned golden yellow",
  newsCropB4:"• Grain moisture 20-25%", newsCropB5:"• Panicle bends downward",
  newsCropB6:"• Leaves turned yellow/brown", newsCropB7:"Harvest timing:",
  newsCropB8:"• Harvest 28-32 days after 50% heading", newsCropB9:"• Morning harvest preferred",
  newsCropB10:"• Avoid wet conditions", newsCropB11:"Post-harvest:",
  newsCropB12:"• Dry grain to 14% moisture before storage",
  newsCropB13:"• Store in clean dry gunny bags", newsCropB14:"• Use neem leaves to prevent pests",
  newsSoilTitle:"Maintaining Optimal Soil pH for Maximum Yield", newsSoilCategory:"Soil Health",
  newsSoilB1:"Soil pH controls nutrient availability.",
  newsSoilB2:"pH and nutrients:", newsSoilB3:"• pH 6.0-7.0: Best for rice, wheat, maize, cotton",
  newsSoilB4:"• pH below 5.5: iron toxicity", newsSoilB5:"• pH above 7.5: phosphorus unavailable",
  newsSoilB6:"Correcting acidic soil:", newsSoilB7:"• Apply lime at 1-2 tons/acre",
  newsSoilB8:"• Use dolomite lime for magnesium", newsSoilB9:"• Allow 2-4 weeks for pH change",
  newsSoilB10:"Correcting alkaline soil:", newsSoilB11:"• Apply sulfur 200-400 kg/acre",
  newsSoilB12:"• Use acidifying fertilizers", newsSoilB13:"• Gypsum for sodic soils",
  newsSoilB14:"Test soil pH twice per year — before Kharif and Rabi seasons.",
  newsIrrigTitle:"Drip Irrigation Efficiency: Getting the Most from Every Litre",
  newsIrrigCategory:"Irrigation Management",
  newsIrrigB1:"Drip irrigation saves 30-50% water and improves yield by 20-30%.",
  newsIrrigB2:"System maintenance:", newsIrrigB3:"• Flush drip lines weekly",
  newsIrrigB4:"• Check emitters monthly", newsIrrigB5:"• Install filters at pump inlet",
  newsIrrigB6:"Scheduling:", newsIrrigB7:"• Irrigate in early morning or evening",
  newsIrrigB8:"• Use sensors to irrigate only when needed",
  newsIrrigB9:"• Reduce irrigation 2 weeks before harvest",
  newsIrrigB10:"Fertigation:", newsIrrigB11:"• Use drip system for fertigation",
  newsIrrigB12:"• Urea and potassium nitrate dissolve well",
  newsIrrigB13:"• Never mix calcium and phosphate in same tank",
  newsIrrigB14:"Set irrigation schedules based on soil type for automatic water calculation.",
  dailyNews1Title:"Today's Farm Advisory Based on Weather", dailyNews1Category:"Weather Advisory",
  dailyNews1B1:"Today's conditions (32°C, partly cloudy) are ideal for pesticide spraying before 9 AM.",
  dailyNews1B2:"Soil moisture at 74% — no irrigation needed today.",
  dailyNews1B3:"UV Index at 6 (High) — wear protective clothing during 11 AM - 3 PM.",
  dailyNews2Title:"June Farming Calendar: What to Do This Week", dailyNews2Category:"Seasonal Tip",
  dailyNews2B1:"Kharif season underway. Ideal for transplanting paddy if soil moisture is 70-80%.",
  dailyNews2B2:"Apply second dose of nitrogen (Urea) to rice — boosts tillering significantly.",
  dailyNews2B3:"Scout fields for stem borer. Spray if infestation exceeds 5% of plants.",
  dailyNews2B4:"Sugarcane earthing-up should be done this week to prevent lodging.",
  dailyNews3Title:"Current Crop Price Trends — June 2026", dailyNews3Category:"Market Update",
  dailyNews3B1:"Rice: Rs.2,100-2,200/quintal. Prices expected to rise 5-8% post-harvest.",
  dailyNews3B2:"Cotton: Rs.6,800-7,000/quintal. Strong demand from textile mills.",
  dailyNews3B3:"Wheat: Rs.2,300/quintal MSP. Market prices stable at Rs.2,350-2,400.",
  dailyNews3B4:"Register on eNAM portal for better price discovery and direct buyer access.",
  notif1Title:"Low Battery Sensor", notif1Body:"Humidity Sensor at 23%. Replace soon.",
  notif2Title:"Rain Forecast", notif2Body:"Heavy rain expected Wednesday. Pause irrigation.",
  notif3Title:"Crop Harvest Ready", notif3Body:"Rice in Field A ready for harvest this week.",
  notif4Title:"pH Level Optimal", notif4Body:"Soil pH at 6.8 — ideal for current crops.",
  notif5Title:"Irrigation Complete", notif5Body:"Field C irrigation completed. 450L used.",
  /* community */
  community:"Farmer Community", communitySub:"Share your farming success and learn from others",
  createPost:"Create Post", createPostSub:"Share your farming experience with the community",
  postTitle:"Post Title", postTitlePlaceholder:"e.g. My best Rice harvest this year!",
  postDescPlaceholder:"Describe your crop, techniques used, what worked well...",
  addPhoto:"Add Photo (optional)", clickToUpload:"Click to upload farm photo",
  publishPost:"Publish Post", noPosts:"No posts yet. Be the first to share!",
  comments:"Comments", writeComment:"Write a comment...", noComments:"No comments yet.",
  /* profit history */
  profitHistory:"Profit History", profitSub:"Track your farm earnings and share your success",
  totalInvestment:"Total Investment", totalRevenue:"Total Revenue", netGain:"Net Gain",
  cropName:"Crop Name", investment:"Investment (₹)", revenue:"Revenue (₹)",
  noProfitHistory:"No profit records yet. Add your first harvest record!",
  /* disease detection */
  diseaseDetection:"Disease Detection & Farm Analysis",
  diseaseDetectionSub:"Upload a crop or farm photo to get AI-powered analysis and solutions",
  analysisHistory:"Detection History",
  /* sensors */
  addIotSensor:"Add IoT Sensor", registerNewSensor:"Register New IoT Sensor",
  sensorName:"Sensor Name", sensorType:"Type", fieldName:"Field Name",
  sensorTypeMulti:"Multi (All)", sensorTypeSoil:"Soil Moisture",
  sensorTypeTemp:"Temperature", sensorTypeHumidity:"Humidity",
  sensorTypePh:"pH Level", sensorTypeNpk:"NPK",
  addSensorBtn:"Add Sensor", addingBtn:"Adding...", closeBtn:"Close",
  sensorAdded:"✅ Sensor Added! Save this Device Key:",
  liveIot:"🔴 Live IoT", mockData:"📊 Mock Data",
  cropRecIot:"AI Crop Recommendation (from IoT Data)", confidenceMatch:"match",
  connectIotTitle:"Connect Your IoT Sensor",
  connectIotDesc:"Currently showing mock data. Once you add a sensor and connect a real IoT device, live data will appear here automatically.",
  /* dashboard */
  shareLearn:"Share & Learn",
  /* profile quick links */
  profitHistoryLink:"💰 Profit History", myPostsLink:"🌾 My Posts", diseaseHistLink:"🔬 Disease History",
  memberSince:"Member since", savingBtn:"Saving...",
  saveError:"Could not save. Please try again.",
  /* create post */
  titleDescRequired:"Title and description required.",
  pleaseLoginFirst:"Please login first.",
  postFailed:"Could not create post. Try again.",
  maxFileSize:"JPG, PNG, WEBP — Max 5MB",
  removePhoto:"✕ Remove Photo",
  posting:"⏳ Posting...",
},

/* ════════════════════════════════════════════
   TAMIL
════════════════════════════════════════════ */
ta: {
  /* nav */
  home:"முகப்பு", dashboard:"டாஷ்போர்டு", farmMgmt:"பண்ணை நிர்வாகம்",
  sensors:"சென்சார் கண்காணிப்பு", crops:"பயிர் ஆலோசனை", irrigation:"நீர்ப்பாசனம்",
  soil:"மண் பகுப்பாய்வு", weather:"வானிலை", reports:"அறிக்கைகள்",
  profile:"சுயவிவரம்", history:"பண்ணை வரலாறு", logout:"வெளியேறு",
  /* auth */
  welcomeBack:"மீண்டும் வரவேற்கிறோம்", signIn:"உங்கள் AgroSmart கணக்கில் உள்நுழையுங்கள்",
  username:"பயனர்பெயர்", password:"கடவுச்சொல்",
  farmer:"விவசாயி", signInBtn:"உள்நுழை", newFarmer:"புதிய விவசாயியா?",
  createAcc:"இலவச கணக்கு உருவாக்கு", orGuest:"அல்லது தொடரவும்",
  guestMode:"விருந்தினர் (பார்வை மட்டும்)", fillAll:"அனைத்து புலங்களையும் நிரப்பவும்.",
  createAccount:"கணக்கு உருவாக்கு", registerSub:"உங்கள் பண்ணையை பதிவு செய்யுங்கள்",
  fullName:"முழு பெயர்", mobile:"மொபைல் எண்", village:"கிராமம் / நகரம்",
  state:"மாநிலம்", farmSize:"பண்ணை அளவு (ஏக்கர்)", primaryCrop:"முதன்மை பயிர்",
  confirmPwd:"கடவுச்சொல் உறுதிப்படுத்தவும்", alreadyHave:"ஏற்கனவே கணக்கு உள்ளதா?",
  passwordsMustMatch:"கடவுச்சொற்கள் பொருந்தவில்லை.", minChars:"குறைந்தது 6 எழுத்துக்கள்",
  farmSizePlaceholder:"எ.கா. 10",
  authStatFree:"இலவசம்", authStatForever:"எப்போதும்",
  authStatSetup:"5 நிமி", authStatSetupLabel:"அமைவு",
  authStat247:"24/7", authStatMonitoring:"கண்காணிப்பு",
  /* home */
  heroTag:"🌱 நவீன இந்தியாவுக்கான ஸ்மார்ட் விவசாயம்",
  heroTitle:"உங்கள் பண்ணையை", heroAccent:"எங்கிருந்தும் கண்காணிக்கவும்",
  heroSub:"உண்மையான நேர மண், வானிலை மற்றும் பயிர் தரவு உங்கள் கைகளில்.",
  goToDash:"டாஷ்போர்டுக்கு செல்லவும்", registerFree:"இலவசமாக பதிவு செய்யவும்",
  featuresTitle:"உங்கள் பண்ணைக்கு தேவையான அனைத்தும்",
  featuresSub:"விவசாயிகளுக்காக கட்டப்பட்ட முழுமையான கண்காணிப்பு தளம்.",
  aboutBadge:"திட்டத்தைப் பற்றி", aboutTitle:"இந்தியாவின் விவசாயிகளுக்காக",
  getStarted:"இலவசமாக தொடங்குங்கள்",
  ctaTitle:"உங்கள் பண்ணையை மாற்ற தயாரா?",
  ctaSub:"AgroSmart பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளோடு சேருங்கள்.",
  featuresLink:"அம்சங்கள்", aboutLink:"பற்றி",
  farmersLabel:"விவசாயிகள்", uptimeLabel:"இயக்க நேரம்",
  waterSavedLabel:"நீர் சேமிப்பு", yieldBoostLabel:"விளைச்சல் மேம்பாடு",
  featureRtSensors:"நேரடி சென்சார்கள்",
  featureRtSensorsDesc:"மண் ஈரப்பதம், வெப்பநிலை, pH மற்றும் ஈரப்பதத்தை உடனடியாக கண்காணிக்கவும்.",
  featureWeather:"வானிலை நுண்ணறிவு",
  featureWeatherDesc:"உள்ளூர் வானிலை முன்னறிவிப்புகள் மற்றும் நீர்ப்பாசன எச்சரிக்கைகள் பெறவும்.",
  featureIrrigation:"ஸ்மார்ட் நீர்ப்பாசனம்",
  featureIrrigationDesc:"மண் ஈரப்பத தரவுகளின் அடிப்படையில் தண்ணீர் நேரத்தை தானாக திட்டமிடுங்கள்.",
  featureCrops:"பயிர் பரிந்துரைகள்",
  featureCropsDesc:"உங்கள் மண் சுயவிவரம் மற்றும் காலநிலைக்கு ஏற்ற பயிர் பரிந்துரைகள்.",
  featureSoil:"மண் ஆரோக்கிய பகுப்பாய்வு",
  featureSoilDesc:"NPK அளவுகள், pH சமநிலை மற்றும் கரிமப்பொருட்களை கண்காணிக்கவும்.",
  featureAnalytics:"பகுப்பாய்வு & அறிக்கைகள்",
  featureAnalyticsDesc:"விரிவான மாதாந்திர அறிக்கைகள் மற்றும் விளைச்சல் கணிப்புகள்.",
  benefitNoTech:"தொழில்நுட்ப அறிவு தேவையில்லை",
  benefitMobile:"மொபைல், டேப்லெட், டெஸ்க்டாப் — எல்லாவற்றிலும் வேலை செய்கிறது",
  benefitLang:"தமிழ், ஹிந்தி, ஆங்கிலம் ஆதரவு",
  benefitAlerts:"நேரடி எச்சரிக்கைகள் மற்றும் அறிவிப்புகள்",
  benefitFree:"சிறு விவசாயிகளுக்கு இலவசம்",
  benefitResearch:"விவசாய ஆராய்ச்சி தரவு ஆதரவு",
  aboutDesc:"AgroSmart இந்திய கிராமப்புற விவசாயிகளுக்கு தேவையான நவீன கண்காணிப்பு தளம்.",
  footerTagline:"ஸ்மார்ட் விவசாய கண்காணிப்பு அமைப்பு",
  footerCopyright:"© 2026 | Capstone Project | React PWA",
  smartAgriPlatform:"ஸ்மார்ட் விவசாய தளம்",
  liveDashboard:"நேரடி டாஷ்போர்டு",
  /* dashboard */
  goodMorning:"காலை வணக்கம்", goodAfternoon:"மதிய வணக்கம்", goodEvening:"மாலை வணக்கம்",
  allSensorsActive:"இன்றைய பண்ணை அவலோகனம். அனைத்து சென்சார்களும் செயலில் உள்ளன.",
  temperature:"வெப்பநிலை", humidity:"ஈரப்பதம்", soilMoisture:"மண் ஈரப்பதம்",
  phLevel:"அமிலத்தன்மை அளவு", weeklyTrends:"வாராந்திர சென்சார் போக்குகள்",
  recentActivity:"சமீபத்திய செயல்பாடுகள்", quickAccess:"விரைவு அணுகல்",
  optimalRange:"பயிர்களுக்கு சரியான வரம்பு", goodMoisture:"காற்றில் நல்ல ஈரப்பதம்",
  wellIrrigated:"நன்கு நீர்ப்பாய்ச்சல்", neutralIdeal:"நடுநிலை — சிறந்தது",
  alertLowBatteryTitle:"குறைந்த பேட்டரி — சென்சார் எச்சரிக்கை",
  alertLowBatteryMsg:"ஈரப்பத சென்சார் (வயல் ஈ) 23% பேட்டரியில் உள்ளது. விரைவில் மாற்றவும்.",
  alertRainTitle:"மழை முன்னறிவிப்பு — நீர்ப்பாசன ஆலோசனை",
  alertRainMsg:"புதன்கிழமை கனமழை எதிர்பார்க்கப்படுகிறது. வயல் இ க்கு நீர்ப்பாசனம் நிறுத்துவதை பரிசீலிக்கவும்.",
  actIrrigation:"வயல் அ-க்கு நீர்ப்பாசனம் தொடங்கியது",
  actLowBattery:"ஈரப்பத சென்சார் (வயல் ஈ) பேட்டரி குறைவு",
  actHarvest:"வயல் ஆ (நெல்) அறுவடை திட்டமிடப்பட்டது",
  actPhReading:"புதிய அமிலத்தன்மை அளவீடு: 6.8 (சிறந்தது)",
  actRainForecast:"அடுத்த 3 நாட்களுக்கு மழை முன்னறிவிப்பு",
  actFertilizer:"கோதுமை வயலில் என்பிகே உரம் இடப்பட்டது",
  /* farm */
  farmMgmtTitle:"பண்ணை நிர்வாகம்", farmMgmtSub:"உங்கள் பண்ணை விவரங்களை நிர்வகிக்கவும்",
  farmDetails:"பண்ணை விவரங்கள்", farmName:"பண்ணை பெயர்", owner:"உரிமையாளர்",
  location:"இடம்", totalArea:"மொத்த பரப்பளவு", established:"நிறுவப்பட்டது",
  soilTypeLabel:"மண் வகை", waterSource:"நீர் ஆதாரம்", activeCrops:"செயலில் உள்ள பயிர்கள்",
  totalFields:"மொத்த வயல்கள்", irrigated:"நீர்ப்பாய்ச்சல்", healthyFields:"ஆரோக்கியமான வயல்கள்",
  needAttention:"கவனம் தேவை", cropCalendar:"பயிர் நாட்காட்டி", fieldOverview:"வயல் அவலோகனம்",
  health:"ஆரோக்கியம்", noIrrigation:"நீர்ப்பாய்ச்சல் இல்லை",
  farmLocation:"கோயம்புத்தூர், தமிழ்நாடு",
  borewellLabel:"ஆழ்துளை கிணறு", canalLabel:"கால்வாய்",
  fieldA:"வயல் அ", fieldB:"வயல் ஆ", fieldC:"வயல் இ", fieldD:"வயல் ஈ",
  allFields:"அனைத்து வயல்களும்",
  cropRice:"நெல்", cropWheat:"கோதுமை", cropSugarcane:"கரும்பு", cropCotton:"பருத்தி",
  cropMaize:"மக்காச்சோளம்", cropSoybean:"சோயாபீன்", cropPulses:"பயறு வகைகள்", cropVegetables:"காய்கறிகள்",
  areaAcre:"ஏக்கர்", seasonKharif:"கரீஃப்", seasonRabi:"ரபி", seasonAnnual:"வருடாந்திரம்",
  irrDrip:"நீர்த்துளி", irrSprinkler:"தெளிப்பான்", irrFurrow:"வாய்க்கால்",
  mJun:"ஜூன்", mJul:"ஜூலை", mAug:"ஆக", mSep:"செப்", mOct:"அக்", mApr:"ஏப்ரல்", mMay:"மே",
  calTask1:"விதைப்பு — நெல் (வயல் அ)", calTask2:"உரமிடல் — கோதுமை (வயல் ஆ)",
  calTask3:"நீர்ப்பாசன அட்டவணை — வயல் இ", calTask4:"பூச்சிக்கொல்லி — பருத்தி (வயல் ஈ)",
  calTask5:"அறுவடை — நெல் (வயல் அ)",
  done:"முடிந்தது", pending:"நிலுவையில்",
  /* sensors */
  sensorMonitor:"சென்சார் கண்காணிப்பு", sensorSub:"உங்கள் வயல்களில் IoT சென்சார்களிலிருந்து நேரடி தரவு",
  totalSensors:"மொத்த சென்சார்கள்", active:"செயலில்", warning:"எச்சரிக்கை", offline:"ஆஃப்லைன்",
  refreshData:"தரவு புதுப்பி", refreshing:"புதுப்பிக்கிறது...", allSensors:"அனைத்து சென்சார்கள்",
  sensorDataLog:"சென்சார் தரவு பதிவு", sensorId:"சென்சார் ID", name:"பெயர்", type:"வகை",
  currentValue:"தற்போதைய மதிப்பு", battery:"பேட்டரி", status:"நிலை", lastUpdate:"கடைசி புதுப்பிப்பு",
  lowBattery:"குறைந்த பேட்டரி — விரைவில் மாற்றவும்",
  lastRefreshed:"கடைசி:", sensorStatusActive:"செயலில்",
  sensorStatusWarning:"எச்சரிக்கை", sensorStatusInactive:"செயலற்றது",
  sensorFieldA:"வயல் அ - மண் சென்சார்", sensorFieldB:"வயல் ஆ - வெப்ப சென்சார்",
  sensorFieldC:"வயல் இ - pH சென்சார்", sensorFieldD:"வயல் ஈ - ஈரப்பத சென்சார்",
  sensorGreenhouse:"கிரீன்ஹவுஸ் - CO₂", sensorFieldE:"வயல் உ - காற்று சென்சார்",
  su2min:"2 நிமிடம் முன்பு", su1min:"1 நிமிடம் முன்பு", su5min:"5 நிமிடம் முன்பு",
  su3min:"3 நிமிடம் முன்பு", su4min:"4 நிமிடம் முன்பு", su2hrs:"2 மணி நேரம் முன்பு",
  /* crops */
  cropAdvice:"பயிர் பரிந்துரைகள்", cropSub:"உங்கள் மண் மற்றும் காலநிலை தரவின் அடிப்படையில் AI பரிந்துரைகள்",
  whyCrop:"இந்த பயிர் ஏன்?", recFertilizer:"பரிந்துரைக்கப்பட்ட உரம் (கிலோ/ஹெக்டேர்)",
  duration:"கால அளவு", waterNeed:"நீர் தேவை", expectedYield:"எதிர்பார்க்கப்படும் விளைச்சல்",
  season:"பருவம்", soilSummary:"மண் பகுப்பாய்வு சுருக்கம்",
  overallScore:"ஒட்டுமொத்த மண் மதிப்பெண்", match:"பொருத்தம்",
  overallScoreNote:"உங்கள் மண் சாகுபடிக்கு நல்ல நிலையில் உள்ளது.",
  downloadSoilReport:"மண் அறிக்கை பதிவிறக்கம்",
  neutral:"நடுநிலை — சிறந்தது", adequate:"போதுமானது", slightlyHigh:"சற்று அதிகம்",
  good:"நல்லது", optimalRng:"சரியான வரம்பு",
  dur120_150:"120-150 நாட்கள்", dur10_12m:"10-12 மாதங்கள்", dur180_200:"180-200 நாட்கள்",
  waterHigh:"அதிகம்", waterMedium:"மிதமான",
  reasonRice:"சரியான மண் அமிலத்தன்மை (6.8), அதிக ஈரப்பதம் (74%), வெப்பநிலை (30-34°C) நெல் சாகுபடிக்கு ஏற்றது.",
  reasonSugarcane:"போதுமான பொட்டாசியம் உள்ள வடிகால் களிமண் மற்றும் வெப்பமான காலநிலை கரும்பு வளர்ச்சியை ஆதரிக்கிறது.",
  reasonCotton:"மிதமான நைட்ரஜன் மற்றும் சூரிய ஒளி உள்ள சிவப்பு களிமண் பருத்தி தேவைகளுக்கு பொருந்துகிறது.",
  yield45:"4.5 டன்/ஏக்கர்", yield35:"35 டன்/ஏக்கர்", yield18:"1.8 டன்/ஏக்கர்",
  stageFlowering:"பூக்கும் நிலை", stageGermination:"முளைப்பு நிலை",
  stageMaturation:"முதிர்ச்சி நிலை", stageBollFormation:"காய் உருவாக்கம்",
  soilScore:"82/100",
  /* irrigation */
  irrigationMgmt:"நீர்ப்பாசன மேலாண்மை", irrigationSub:"உண்மையான நேரத்தில் நீர்ப்பாசன அமைப்புகளை கட்டுப்படுத்துங்கள்",
  waterToday:"இன்று பயன்படுத்திய நீர்", thisWeek:"இந்த வாரம்", efficiency:"திறன்",
  nextScheduled:"அடுத்த திட்டம்", motorControl:"மோட்டார் கட்டுப்பாடு",
  mainPumpMotor:"முக்கிய பம்ப் மோட்டார்", running:"இயங்குகிறது", stopped:"நிறுத்தப்பட்டது",
  pumpOffline:"பம்ப் ஆஃப்லைனில் உள்ளது", startMotor:"மோட்டார் தொடங்கு", stopMotor:"மோட்டார் நிறுத்து",
  fieldStatus:"வயல் நிலை", irrigAlerts:"நீர்ப்பாசன எச்சரிக்கைகள்",
  startTime:"தொடக்க நேரம்", endTime:"முடிவு நேரம்", schedule:"திட்டமிடு",
  waterReq:"தேவையான நீர்", scheduleIrrigation:"நீர்ப்பாசனம் திட்டமிடு",
  flow:"ஓட்டம்", dripIrrigation:"நீர்த்துளி பாசனம்",
  motorRuntime:"மோட்டார் இயக்க நேரம்", powerConsumption:"மின் நுகர்வு",
  motorRuntimeVal:"4 மணி 20 நிமிடம்", powerConsumptionVal:"2.4 கிலோவாட் மணி",
  fieldStatus_irrigating:"நீர்ப்பாய்ச்சல்", fieldStatus_scheduled:"திட்டமிடப்பட்டது",
  fieldStatus_completed:"முடிந்தது", fieldStatus_off:"நிறுத்தம்",
  tomorrowAM:"நாளை காலை 6 மணி",
  irrDur1:"2 மணி நேரம் உள்ளது", irrDur2:"நாளை காலை 6 மணி", irrDur3:"காலை 10 மணிக்கு முடிந்தது",
  irrFlow:"45 லி/நிமிடம்",
  irrAlert1:"வயல் ஈ மண் ஈரப்பதம் மிகக் குறைவு (42%). உடனடி நீர்ப்பாசனம் பரிந்துரைக்கப்படுகிறது.",
  irrAlert2:"2 நாட்களில் மழை எதிர்பார்க்கப்படுகிறது. வயல் இ க்கு நீர்ப்பாசனம் குறைப்பதை பரிசீலிக்கவும்.",
  irrAlert3:"வயல் அ நீர்ப்பாசன திறன் 91% — சிறந்த செயல்திறன்.",
  swrSandyLoam:"வேகமாக வடிகிறது — குறுகிய இடைவேளைகளில் அடிக்கடி பாசனம் செய்யவும்.",
  swrClayLoam:"நன்கு நீர் தேக்கும் — அதிக நீர் பாசனம் தவிர்க்கவும்.",
  swrSiltLoam:"சமன் வடிகால் — சாதாரண அட்டவணை பொருந்தும்.",
  swrRedLoam:"மிதமான வடிகால் — ஈரப்பதத்தை நெருக்கமாக கண்காணிக்கவும்.",
  swrBlackCotton:"நீர் தேக்கும் திறன் அதிகம் — பாசன அதிர்வெண்ணை குறைக்கவும்.",
  swrUnit:"லி/ஏக்கர்/மணி",
  /* soil */
  soilAnalysis:"மண் பகுப்பாய்வு", soilSub:"உங்கள் வயல்களில் மண் ஆரோக்கிய அளவுருக்களை கண்காணிக்கவும்",
  nitrogen:"நைட்ரஜன் (N)", phosphorus:"பாஸ்பரஸ் (P)", potassium:"பொட்டாசியம் (K)",
  phLevelLabel:"அமிலத்தன்மை அளவு", organicMatter:"கரிமப்பொருள்",
  soilTemp:"வெப்பநிலை", moisture:"ஈரப்பதம்", ideal:"சிறந்தது",
  phSimulator:"அமிலத்தன்மை சிமுலேட்டர்", soilNutrient:"மண் ஊட்டச்சத்து சுயவிவரம்",
  soilType:"மண் வகை", waterNeeded:"தேவையான நீர்", waterSchedule:"நீர்ப்பாசன அட்டவணை",
  bestCrops:"சிறந்த பயிர்கள்", drainage:"வடிகால்",
  veryAcidic:"மிகவும் அமிலம்", slightlyAcidic:"சற்று அமிலம்",
  neutralIdealPh:"நடுநிலை — சிறந்தது", slightlyAlkaline:"சற்று காரம்", veryAlkaline:"மிகவும் காரம்",
  addLimeTip:"அமிலத்தன்மை உயர்த்த சுண்ணாம்பு சேர்க்கவும்",
  teaBerryTip:"தேயிலை, பழங்களுக்கு பொருத்தமானது",
  optimalCropTip:"பெரும்பாலான பயிர்களுக்கு சிறந்தது",
  addSulfurTip:"அமிலத்தன்மை குறைக்க கந்தகம் சேர்க்கவும்",
  poorNutrientTip:"ஊட்டச்சத்து கிடைக்கவில்லை",
  lowOrganicTitle:"வயல் ஈ இல் குறைந்த கரிம பொருள்",
  lowOrganicMsg:"கரிம பொருள் 1.8% — சரியான வரம்பிற்கு கீழே. அடுத்த பருவத்திற்கு முன் உரம் சேர்க்கவும்.",
  soilDrainage:"வடிகால்", bestCropsLabel:"சிறந்த பயிர்கள்",
  currentSoilLabel:"தற்போதைய மண்", idealLabel:"சிறந்தது",
  requiredLabel:"தேவையானது", basedOnLabel:"அடிப்படையில்",
  soilSandyLoam:"மணல் களிமண்", soilClayLoam:"ஒட்டும் களிமண்", soilSiltLoam:"மட்டு களிமண்",
  soilRedLoam:"சிவப்பு களிமண்", soilBlackCotton:"கருப்பு பருத்தி மண்",
  scSandyLoam:"நெல், வேர்க்கடலை, காய்கறிகள்", scClayLoam:"பருத்தி, கரும்பு, சோயாபீன்",
  scSiltLoam:"கோதுமை, மக்காச்சோளம், சூரியகாந்தி", scRedLoam:"பருத்தி, வேர்க்கடலை, பயறு",
  scBlackCotton:"பருத்தி, சோளம், கொண்டைக்கடலை",
  spSandyLoam:"வேகமாக வடிகிறது — குறுகிய இடைவேளைகளில் பாசனம் செய்யவும்.",
  spClayLoam:"நீர் மற்றும் ஊட்டச்சத்துக்களை நன்கு தேக்கும். வடிகால் வசதி உறுதி செய்யவும்.",
  spSiltLoam:"சமன் வடிகால். சாதாரண பாசனத்துடன் பெரும்பாலான பயிர்களுக்கு சிறந்தது.",
  spRedLoam:"நல்ல இரும்பு சத்து. மிதமான நீர் தேவை. pH பணப்பயிர்களுக்கு ஏற்றது.",
  spBlackCotton:"நீர் தேக்கும் திறன் மிக அதிகம். பாசன அதிர்வெண்ணை கணிசமாக குறைக்கவும்.",
  drainFast:"வேகமான", drainSlow:"மெதுவான", drainModerate:"மிதமான", drainVerySlow:"மிகவும் மெதுவான",
  /* weather */
  weatherOverview:"வானிலை அவலோகனம்", weatherSub:"உங்கள் பண்ணை இடத்திற்கான முன்னறிவிப்பு",
  dayForecast:"7-நாள் முன்னறிவிப்பு", farmImpact:"பண்ணை தாக்க பகுப்பாய்வு",
  recommendations:"பரிந்துரைகள்", farmNews:"பண்ணை செய்திகள்",
  partlyCloudy:"பகுதியளவு மேகமூட்டம்", humidity_lbl:"ஈரப்பதம்", wind:"காற்று",
  rainfall:"மழை", uvIndex:"UV குறியீடு", visibility:"தெரிவுத்தன்மை", pressure:"அழுத்தம்",
  today:"இன்று", tomorrow:"நாளை",
  riceImpact:"பயனளிக்கும் — மழை நீர்ப்பாசன தேவையை குறைக்கும்",
  wheatImpact:"எச்சரிக்கை — அதிக ஈரப்பதம் பூஞ்சை பிரச்சினையை ஏற்படுத்தலாம்",
  sugarcaneImpact:"சிறந்தது — சூடான வானிலை வளர்ச்சியை ஆதரிக்கிறது",
  cottonImpact:"கண்காணி — கனமழை திறந்த காய்களை சேதப்படுத்தலாம்",
  tip1:"வயல் அ மற்றும் இ க்கு நீர்ப்பாசனம் நிறுத்துங்கள்",
  tip2:"புதன்கிழமை மழைக்கு முன் கோதுமை பயிருக்கு பூஞ்சாணக்கொல்லி தெளிக்கவும்",
  tip3:"வயல் ஈ பருத்தியை வியாழக்கிழமை மழைக்கு முன் அறுவடை செய்யவும்",
  tip4:"நீர்த்தேக்கம் தடுக்க தாழ்வான வயல்களில் வடிகால்களை சரிபார்க்கவும்",
  weatherSunny:"வெயில்", weatherClearSky:"தெளிவான வானம்", weatherUvHigh:"(அதிகம்)",
  impactRiceCrop:"நெல் (வயல் அ)", impactWheatCrop:"கோதுமை (வயல் ஆ)",
  impactSugarCrop:"கரும்பு (வயல் இ)", impactCottonCrop:"பருத்தி (வயல் ஈ)",
  weatherHumidity:"68%", weatherWindSpeed:"14 கி.மீ/மணி",
  weatherRainfall:"12 மி.மீ", weatherUvValue:"6",
  weatherVisibility:"8 கி.மீ", weatherPressure:"1012 ஹெக்டோ பாஸ்கல்", weatherTemp:"33°செ",
  /* reports */
  reportsAnalytics:"அறிக்கைகள் & பகுப்பாய்வு", reportsSub:"விரிவான நுண்ணறிவு மற்றும் செயல்திறன் தரவு",
  totalWater:"மொத்த நீர் பயன்பாடு", avgSoil:"சராசரி மண் ஆரோக்கியம்", cropYield:"பயிர் விளைச்சல்",
  activeAlerts:"செயலில் உள்ள எச்சரிக்கைகள்", monthSummary:"மாதாந்திர சுருக்கம்",
  exportPDF:"முழு அறிக்கை ஏற்றுமதி (PDF)", downloadCSV:"CSV பதிவிறக்கம்",
  month:"மாதம்", water:"நீர்", temp:"வெப்பம்", yield:"விளைச்சல்",
  rainfallVsTemp:"மழை vs வெப்பநிலை (வருடாந்திர)",
  monthlyCropYield:"மாதாந்திர பயிர் விளைச்சல்", waterSourceDist:"நீர் மூலம் விநியோகம்",
  soilCol:"மண்", rainfallMm:"மழை (மிமீ)", avgTempC:"சராசரி வெப்பநிலை (°C)", cropYieldPct:"பயிர் விளைச்சல் (%)",
  dripIrrigationLabel:"நீர்த்துளி பாசனம்", rainwaterLabel:"மழைநீர்",
  rptPdfTitle:"AgroSmart பண்ணை அறிக்கை", rptGenerated:"உருவாக்கப்பட்டது:",
  rptPdfFooter:"AgroSmart - ஸ்மார்ட் விவசாய கண்காணிப்பு அமைப்பால் உருவாக்கப்பட்டது",
  rptPdfFilename:"AgroSmart_Report.txt", rptCsvFilename:"AgroSmart_Summary.csv",
  rptTotalWater:"மொத்த நீர் பயன்பாடு", rptWaterVal:"28,450 லி",
  rptAvgSoil:"சராசரி மண் ஆரோக்கியம்", rptSoilVal:"80%",
  rptCropYield:"பயிர் விளைச்சல்", rptYieldVal:"4.2 டன்/ஏக்கர்", rptActiveAlerts:"செயலில் உள்ள எச்சரிக்கைகள்",
  reportWaterUnit:"லி", reportTempUnit:"°செ", reportYieldUnit:"டன்/ஏக்கர்",
  /* units */
  unitKmh:"கி.மீ/மணி", unitMm:"மி.மீ", unitC:"°செ",
  unitL:"லி", unitKg:"கி", unitMg:"மி.கி", unitG:"கி",
  unitKgHa:"கி/ஹெக்.", unitMgKg:"மி.கி/கி", unitPpm:"பிபிஎம்",
  unitTAc:"டன்/ஏக்கர்", unitKwh:"கிலோவாட் மணி", unitHpa:"ஹெக்டோ பாஸ்கல்",
  unitPercent:"%", unitAcre:"ஏக்கர்", unitLMin:"லி/நிமிடம்", unitLAcHr:"லி/ஏக்கர்/மணி",
  unitKg_s:"கி", unitLitres:"லி", unitBags:"பைகள்", unitGrams:"கிராம்", unitMl:"மி.லி",
  timeAM:"காலை", timePM:"மாலை",
  minAgo:"நிமிடம் முன்பு", hrAgo:"மணி நேரம் முன்பு", hrsAgo:"மணி நேரங்கள் முன்பு",
  /* farm history */
  farmHistory:"பண்ணை வரலாறு", historySub:"வார வாரம் அனைத்து பண்ணை செயல்பாடுகளையும் கண்காணிக்கவும்",
  addActivity:"செயல்பாடு சேர்", activityType:"செயல்பாடு வகை", quantity:"அளவு",
  notes:"குறிப்புகள்", date:"தேதி", noHistory:"வரலாறு இல்லை. பண்ணை செயல்பாடுகளை பதிவு செய்யத் தொடங்குங்கள்.",
  field:"வயல்", unit:"அலகு", aiSuggestion:"AI பரிந்துரை", weekOf:"வாரம்",
  fieldLabel:"வயல்", all:"அனைத்தும்", optionalNotes:"விருப்ப குறிப்புகள்",
  aiSuggestionPrefix:"AI பரிந்துரை:",
  lastUsedMsg:"கடைசியாக பயன்படுத்தியது", considerSimilar:"இந்த வாரம் இதே அளவை பரிசீலிக்கவும்.",
  histPlaceholder:"எ.கா. 25",
  act_urea:"யூரியா இடுதல்", act_pesticide:"பூச்சிக்கொல்லி தெளிப்பு",
  act_npk:"உரமிடல் (என்பிகே)", act_dap:"DAP இடுதல்",
  act_potash:"பொட்டாஷ் இடுதல்", act_organic:"கரிம உரம்",
  act_irrigation:"நீர்ப்பாசனம்", act_soilTest:"மண் பரிசோதனை",
  act_harvest:"அறுவடை", act_sowing:"விதைப்பு / நடவு",
  act_weeding:"களை எடுத்தல்", act_fungicide:"பூஞ்சாணக்கொல்லி தெளிப்பு", act_other:"மற்றவை",
  /* profile / settings */
  myProfile:"என் சுயவிவரம்", editProfile:"சுயவிவரம் திருத்து", saveProfile:"சுயவிவரம் சேமி",
  deleteAccount:"கணக்கை நீக்கு", confirmDelete:"உங்கள் கணக்கை நீக்க விரும்புகிறீர்களா?",
  profileUpdated:"சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!", settings:"அமைப்புகள்",
  dangerZone:"ஆபத்தான பகுதி", dangerNote:"உங்கள் கணக்கை நீக்குவது அனைத்து தரவையும் நிரந்தரமாக அழிக்கும்.",
  settingsTitle:"அமைப்புகள்", darkMode:"இருண்ட பயன்முறை", lightMode:"ஒளி பயன்முறை",
  toggleTheme:"பயன்பாட்டு தீம் மாற்றவும்", languageLabel:"மொழி",
  languageSub:"விருப்பமான மொழியை தேர்ந்தெடுக்கவும்",
  guestBrowsingMsg:"நீங்கள் விருந்தினர் பயன்முறையில் உலாவுகிறீர்கள். தரவை சேமிக்க பதிவு செய்யவும்.",
  yesDelete:"ஆம், நீக்கவும்",
  notifications:"அறிவிப்புகள்", markAllRead:"அனைத்தையும் படித்ததாக குறி", noNotifications:"புதிய அறிவிப்புகள் இல்லை",
  save:"சேமி", cancel:"ரத்து செய்", edit:"திருத்து", delete:"நீக்கு", update:"புதுப்பி",
  search:"தேடு", filter:"வடிகட்டு", export:"ஏற்றுமதி", download:"பதிவிறக்கம்",
  selectState:"மாநிலத்தை தேர்ந்தெடுக்கவும்", selectCrop:"பயிரை தேர்ந்தெடுக்கவும்", liveMode:"நேரடி",
  farmSizePlaceholder:"எ.கா. 10",
  /* fertilizer */
  fertilizerRec:"உர பரிந்துரை",
  fertilizerSub:"பயிர் வகை மற்றும் மண் தரவின் அடிப்படையில் AI உர பரிந்துரைகள்",
  selectCropLabel:"பயிரை தேர்ந்தெடுக்கவும்", recommendationLabel:"பரிந்துரை",
  pleaseSelectCrop:"பரிந்துரை பார்க்க ஒரு பயிரை தேர்ந்தெடுக்கவும்",
  npkFertilizer:"NPK உரம்", ureaFertilizer:"யூரியா",
  dapFertilizer:"DAP", potashFertilizer:"பொட்டாஷ்",
  fertilizerDetails:"உர விவரங்கள்", applicationRate:"பயன்பாட்டு விகிதம்",
  applicationTime:"பயன்பாட்டு நேரம்", benefits:"நன்மைகள்",
  precautions:"முன்னெச்சரிக்கைகள்", mixingInstructions:"கலைவு வழிமுறைகள்",
  fertRateRice:"90-60-40 கி/ஹெக்.", fertTimeRice:"அடிக்கட்டு + பயிர்பிடிப்பு",
  fertBenRice:"பயிர்பிடிப்பு மற்றும் தானிய நிரப்பு மேம்படும்",
  fertPrecRice:"நைட்ரஜனை பிரித்து இடவும்", fertMixRice:"நடவுக்கு முன் தூவி இடவும்",
  fertRateWheat:"60-30-30 கி/ஹெக்.", fertTimeWheat:"விதைப்பு + 21 நாட்கள்",
  fertBenWheat:"வலுவான வேர் வளர்ச்சி",
  fertPrecWheat:"DAP பிறகு நீர்த்தேக்கம் தவிர்க்கவும்", fertMixWheat:"உலர் மண்ணுடன் கலந்து தெளிக்கவும்",
  fertRateCotton:"60-30-60 கி/ஹெக்.", fertTimeCotton:"45 மற்றும் 75 நாட்கள்",
  fertBenCotton:"காய் உருவாக்கம், நார் தரம்",
  fertPrecCotton:"அதிகமாக இட வேண்டாம் — இலை எரிவு ஏற்படும்", fertMixCotton:"நீரில் கரைத்து இடவும்",
  fertRateSugarcane:"120-60-120 கி/ஹெக்.", fertTimeSugarcane:"நடவு + கட்டை",
  fertBenSugarcane:"வேகமான தாவர வளர்ச்சி",
  fertPrecSugarcane:"3 தவணைகளில் பிரித்து இடவும்", fertMixSugarcane:"வேர் பகுதியில் தூவி இடவும்",
  /* admin */
  adminPanel:"நிர்வாகி பேனல்", systemHealthy:"அமைப்பு நலமாக உள்ளது",
  uptimeMonth:"இந்த மாதம் இயக்க நேரம்", systemOpsMsg:"அமைப்பு நிலை: அனைத்தும் இயங்குகின்றன.",
  registeredFarmers:"பதிவு செய்யப்பட்ட விவசாயிகள்", goToFarmerDash:"விவசாயி டாஷ்போர்டுக்கு செல்லவும்",
  nameCol:"பெயர்", villageCol:"கிராமம்", cropCol:"பயிர்", areaCol:"பரப்பளவு", statusCol:"நிலை",
  farmerActive:"செயலில்", farmerInactive:"செயலற்றது",
  adminFarmer1Name:"ராஜேஷ் குமார்", adminFarmer1Village:"பொள்ளாச்சி",
  adminFarmer2Name:"பிரியா தேவி", adminFarmer2Village:"ஈரோடு",
  adminFarmer3Name:"சுரேஷ் பாபு", adminFarmer3Village:"சேலம்",
  adminFarmer4Name:"கவிதா எம்.", adminFarmer4Village:"மதுரை",
  /* news */
  newsNotFound:"கட்டுரை கிடைக்கவில்லை", newsGoBack:"திரும்பு", newsBack:"பின்",
  newsTodayFarmNews:"இன்றைய பண்ணை செய்திகள்",
  newsReadTime3:"3 நிமிட வாசிப்பு", newsReadTime4:"4 நிமிட வாசிப்பு", newsReadTime5:"5 நிமிட வாசிப்பு",
  newsAlertTitle:"சென்சார் பேட்டரி ஆயுள் & பராமரிப்பு",
  newsAlertCategory:"சென்சார் பராமரிப்பு",
  newsAlertB1:"IoT மண் சென்சார்கள் ஒரு சார்ஜில் 6-12 மாதங்கள் இயங்கும். குறைந்த பேட்டரி தவறான அளவீடுகளை ஏற்படுத்தலாம்.",
  newsAlertB2:"சிறந்த நடைமுறைகள்:", newsAlertB3:"• வாரந்தோறும் பேட்டரி அளவை சரிபார்க்கவும்",
  newsAlertB4:"• 25%-க்கு கீழே இறங்கும்போது மாற்றவும்", newsAlertB5:"• மாதந்தோறும் சுத்தம் செய்யவும்",
  newsAlertB6:"• நேரடி சூரிய ஒளியில் வைக்க வேண்டாம்", newsAlertB7:"• குளிர்ந்த இடத்தில் வையுங்கள்",
  newsAlertB8:"ஈரப்பத சென்சார்கள் பேட்டரி சேதத்திற்கு மிகவும் உணர்திறன் உடையவை.",
  newsWeatherTitle:"கனமழைக்கு உங்கள் பண்ணையை தயார்படுத்துவது எப்படி",
  newsWeatherCategory:"வானிலை ஆலோசனை",
  newsWeatherB1:"கனமழை நீர்த்தேக்கம் மற்றும் பயிர் சேதத்தை ஏற்படுத்தலாம்.",
  newsWeatherB2:"வடிகால் தயாரிப்பு:", newsWeatherB3:"• மழைக்கு முன் வடிகால் கால்வாய்களை சுத்தம் செய்யவும்",
  newsWeatherB4:"• வரம்புகள் சரியாக இருக்கட்டும்", newsWeatherB5:"• தாழ்வான பகுதிகளில் தற்காலிக பம்புகள் நிறுவுங்கள்",
  newsWeatherB6:"பயிர் பாதுகாப்பு:", newsWeatherB7:"• மழைக்கு 48 மணி நேரத்திற்கு முன் உரம் இட வேண்டாம்",
  newsWeatherB8:"• சாய்வு தடுக்க உயரமான பயிர்களை கட்டுங்கள்", newsWeatherB9:"• முதிர்ந்த பயிர்களை உடனடியாக அறுவடை செய்யவும்",
  newsWeatherB10:"நீர்ப்பாசனம்:", newsWeatherB11:"• மழைக்கு 24-48 மணி நேரத்திற்கு முன் பாசனம் நிறுத்துங்கள்",
  newsWeatherB12:"• மழைக்கு பின் மோட்டார் பம்புகளை அணைத்து சரிபார்க்கவும்",
  newsWeatherB13:"மழை பின் படிகள்:", newsWeatherB14:"• கனமழைக்கு பின் மண் pH சோதிக்கவும்",
  newsWeatherB15:"• ஈரமான நிலைகளில் பூஞ்சை நோய்களை கண்காணிக்கவும்",
  newsCropTitle:"நெல் அறுவடை: தயார்நிலை அறிகுறிகள்", newsCropCategory:"பயிர் மேலாண்மை",
  newsCropB1:"சரியான நேரத்தில் அறுவடை தானிய தரம் மற்றும் விளைச்சலை அதிகரிக்கும்.",
  newsCropB2:"நெல் தயாரான அறிகுறிகள்:", newsCropB3:"• 80-85% தானியங்கள் தங்க மஞ்சள் நிறம்",
  newsCropB4:"• தானிய ஈரப்பதம் 20-25%", newsCropB5:"• தானிய எடையில் கதிர் கீழ்நோக்கி வளைகிறது",
  newsCropB6:"• இலைகள் மஞ்சள்/பழுப்பு நிறமாக மாறியிருக்கும்",
  newsCropB7:"அறுவடை நேரம்:", newsCropB8:"• 50% கதிர் தோன்றிய 28-32 நாட்களுக்கு பிறகு அறுவடை",
  newsCropB9:"• காலை அறுவடை விரும்பத்தக்கது", newsCropB10:"• ஈரமான நிலைகளில் அறுவடை தவிர்க்கவும்",
  newsCropB11:"அறுவடை பின்:", newsCropB12:"• 14% ஈரப்பதத்திற்கு உலர்த்தவும்",
  newsCropB13:"• சுத்தமான, உலர்ந்த சாக்கு பைகளில் சேமிக்கவும்",
  newsCropB14:"• வேப்பிலை பயன்படுத்தி பூச்சி தாக்குதல் தடுக்கவும்",
  newsSoilTitle:"அதிகபட்ச விளைச்சலுக்கு சரியான மண் pH பராமரிப்பு", newsSoilCategory:"மண் ஆரோக்கியம்",
  newsSoilB1:"மண் pH ஊட்டச்சத்து கிடைக்கும் தன்மையை கட்டுப்படுத்துகிறது.",
  newsSoilB2:"pH மற்றும் ஊட்டச்சத்து:", newsSoilB3:"• pH 6.0-7.0: நெல், கோதுமை, மக்காச்சோளம், பருத்திக்கு சிறந்தது",
  newsSoilB4:"• pH 5.5-க்கு கீழ்: இரும்பு நச்சு", newsSoilB5:"• pH 7.5-க்கு மேல்: பாஸ்பரஸ் கிடைக்காது",
  newsSoilB6:"அமில மண் சரிசெய்தல்:", newsSoilB7:"• 1-2 டன்/ஏக்கர் வேளாண் சுண்ணாம்பு இடவும்",
  newsSoilB8:"• மெக்னீசியம் சேர்க்க டோலமைட் சுண்ணாம்பு பயன்படுத்துங்கள்",
  newsSoilB9:"• 2-4 வாரங்கள் அனுமதிக்கவும்",
  newsSoilB10:"காரமண் சரிசெய்தல்:", newsSoilB11:"• 200-400 கி/ஏக்கர் கந்தகம் இடவும்",
  newsSoilB12:"• அமில உரங்கள் பயன்படுத்துங்கள்", newsSoilB13:"• சோடிக் மண்ணில் ஜிப்சம் பயன்படுத்துங்கள்",
  newsSoilB14:"வருடத்தில் குறைந்தது இரு முறை மண் pH சோதிக்கவும்.",
  newsIrrigTitle:"நீர்த்துளி பாசன திறன்: ஒவ்வொரு லிட்டரையும் சிறப்பாக பயன்படுத்துதல்",
  newsIrrigCategory:"நீர்ப்பாசன மேலாண்மை",
  newsIrrigB1:"நீர்த்துளி பாசனம் 30-50% நீர் சேமிக்கலாம் மற்றும் விளைச்சலை 20-30% மேம்படுத்தலாம்.",
  newsIrrigB2:"அமைப்பு பராமரிப்பு:", newsIrrigB3:"• வாரந்தோறும் நீர் ஓட்டவும்",
  newsIrrigB4:"• மாதந்தோறும் அடைப்புகளை சரிபார்க்கவும்", newsIrrigB5:"• பம்பில் வடிகட்டிகளை நிறுவுங்கள்",
  newsIrrigB6:"திட்டமிடல்:", newsIrrigB7:"• அதிகாலை அல்லது மாலை பாசனம் செய்யவும்",
  newsIrrigB8:"• சென்சார் மூலம் கண்காணித்து மட்டுமே பாசனம் செய்யவும்",
  newsIrrigB9:"• அறுவடைக்கு 2 வாரங்கள் முன் பாசனம் குறைக்கவும்",
  newsIrrigB10:"உர இடல்:", newsIrrigB11:"• ஃபெர்டிகேஷனுக்கு நீர்த்துளி அமைப்பு பயன்படுத்துங்கள்",
  newsIrrigB12:"• யூரியா மற்றும் பொட்டாசியம் நைட்ரேட் நன்கு கரையும்",
  newsIrrigB13:"• ஒரே டேங்கில் கால்சியம் மற்றும் பாஸ்பேட் கலைக்க வேண்டாம்",
  newsIrrigB14:"தானியங்கி நீர் தேவை கணிப்பிற்கு மண் வகை அடிப்படையில் அட்டவணை அமைக்கவும்.",
  dailyNews1Title:"இன்றைய வானிலை அடிப்படையிலான பண்ணை ஆலோசனை", dailyNews1Category:"வானிலை ஆலோசனை",
  dailyNews1B1:"இன்றைய நிலைகள் (32°C, பகுதி மேகமூட்டம்) பூச்சிக்கொல்லி தெளிக்க சிறந்தவை.",
  dailyNews1B2:"மண் ஈரப்பதம் 74% — இன்று பாசனம் தேவையில்லை.",
  dailyNews1B3:"UV குறியீடு 6 (அதிகம்) — காலை 11 மணி – மாலை 3 மணி வரை பாதுகாப்பு ஆடை அணியவும்.",
  dailyNews2Title:"ஜூன் விவசாய நாட்காட்டி: இந்த வாரம் என்ன செய்வது", dailyNews2Category:"பருவகால குறிப்பு",
  dailyNews2B1:"கரீஃப் பருவம் தொடங்கியது. நெல் நாற்று நடவுக்கு இந்த வாரம் சிறந்தது.",
  dailyNews2B2:"நெல் பயிர்களுக்கு இரண்டாவது நைட்ரஜன் உர தவணை இடவும்.",
  dailyNews2B3:"நெல்லில் தண்டு துளைப்பான் தாக்குதலை கண்காணிக்கவும்.",
  dailyNews2B4:"மழைக்காலத்தில் சாய்வு தடுக்க கரும்பு மண் அணைக்கும் பணியை இந்த வாரம் செய்யவும்.",
  dailyNews3Title:"தற்போதைய பயிர் விலை போக்குகள் — ஜூன் 2026", dailyNews3Category:"சந்தை புதுப்பிப்பு",
  dailyNews3B1:"நெல்: ₹2,100-2,200/குவிண்டால். அறுவடை பருவத்திற்கு பிறகு விலை உயர எதிர்பார்க்கப்படுகிறது.",
  dailyNews3B2:"பருத்தி: ₹6,800-7,000/குவிண்டால். ஜவுளி ஆலைகளிடம் வலுவான தேவை.",
  dailyNews3B3:"கோதுமை: ₹2,300/குவிண்டால் MSP. சந்தை விலை ₹2,350-2,400/குவிண்டால் நிலையாக உள்ளது.",
  dailyNews3B4:"சிறந்த விலை கண்டுபிடிப்பிற்கு eNAM போர்ட்டலில் பதிவு செய்யுங்கள்.",
  notif1Title:"குறைந்த பேட்டரி சென்சார்", notif1Body:"ஈரப்பத சென்சார் 23%-ல் உள்ளது. விரைவில் மாற்றவும்.",
  notif2Title:"மழை முன்னறிவிப்பு", notif2Body:"புதன்கிழமை கனமழை. நீர்ப்பாசனம் நிறுத்துங்கள்.",
  notif3Title:"பயிர் அறுவடை தயார்", notif3Body:"வயல் அ-வில் நெல் இந்த வாரம் அறுவடைக்கு தயார்.",
  notif4Title:"pH அளவு சிறந்தது", notif4Body:"மண் pH 6.8 — தற்போதைய பயிர்களுக்கு சரியானது.",
  notif5Title:"நீர்ப்பாசனம் முடிந்தது", notif5Body:"வயல் இ நீர்ப்பாசனம் முடிந்தது. 450 லி பயன்படுத்தியது.",
  /* community — Tamil */
  community:"விவசாயி சமூகம்", communitySub:"உங்கள் விவசாய வெற்றியை பகிர்ந்து மற்றவரிடம் கற்றுக்கொள்ளுங்கள்",
  createPost:"பதிவு உருவாக்கு", createPostSub:"உங்கள் விவசாய அனுபவத்தை சமூகத்துடன் பகிருங்கள்",
  postTitle:"பதிவு தலைப்பு", postTitlePlaceholder:"எ.கா. இந்த ஆண்டு என் சிறந்த நெல் அறுவடை!",
  postDescPlaceholder:"பயிர், பயன்படுத்திய நுட்பங்கள், என்ன நன்றாக நடந்தது என்று விவரிக்கவும்...",
  addPhoto:"புகைப்படம் சேர் (விருப்பம்)", clickToUpload:"பண்ணை புகைப்படம் பதிவேற்ற கிளிக் செய்யவும்",
  publishPost:"பதிவை வெளியிடு", noPosts:"இன்னும் பதிவுகள் இல்லை. முதலில் பகிருங்கள்!",
  comments:"கருத்துகள்", writeComment:"கருத்து எழுதுங்கள்...", noComments:"இன்னும் கருத்துகள் இல்லை.",
  /* profit history — Tamil */
  profitHistory:"லாப வரலாறு", profitSub:"உங்கள் பண்ணை வருவாயை கண்காணித்து வெற்றியை பகிருங்கள்",
  totalInvestment:"மொத்த முதலீடு", totalRevenue:"மொத்த வருவாய்", netGain:"நிகர லாபம்",
  cropName:"பயிர் பெயர்", investment:"முதலீடு (₹)", revenue:"வருவாய் (₹)",
  noProfitHistory:"இன்னும் லாப பதிவுகள் இல்லை. முதல் அறுவடை பதிவை சேருங்கள்!",
  /* disease detection — Tamil */
  diseaseDetection:"நோய் கண்டறிதல் & பண்ணை பகுப்பாய்வு",
  diseaseDetectionSub:"பயிர் அல்லது பண்ணை புகைப்படத்தை பதிவேற்றி AI பகுப்பாய்வு பெறுங்கள்",
  analysisHistory:"கண்டறிதல் வரலாறு",
  /* irrigation weather — Tamil */
  motorControl:"மோட்டார் கட்டுப்பாடு", autoWeatherMode:"தானியங்கி வானிலை பயன்முறை",
  autoWeatherDesc:"மழை முன்னறிவிப்பு அடிப்படையில் மோட்டார் ON/OFF",
  weatherForLand:"உங்கள் நிலத்திற்கான வானிலை", setLocation:"இடத்தை அமை",
  motorRecommendation:"மோட்டார் பரிந்துரை", rainExpected:"மழை எதிர்பார்க்கப்படுகிறது",
  noRainExpected:"மழை இல்லை — நீர்ப்பாசனம் தேவை",
  runAutoDecision:"தானியங்கி முடிவை இப்போது இயக்கு",
  motorActivityLog:"மோட்டார் செயல்பாடு பதிவு",
  /* sensors — Tamil */
  addIotSensor:"IoT சென்சார் சேர்", registerNewSensor:"புதிய IoT சென்சார் பதிவு",
  sensorName:"சென்சார் பெயர்", sensorType:"வகை", fieldName:"வயல் பெயர்",
  sensorTypeMulti:"அனைத்தும்", sensorTypeSoil:"மண் ஈரப்பதம்",
  sensorTypeTemp:"வெப்பநிலை", sensorTypeHumidity:"ஈரப்பதம்",
  sensorTypePh:"அமிலத்தன்மை", sensorTypeNpk:"என்பிகே",
  addSensorBtn:"சென்சார் சேர்", addingBtn:"சேர்க்கிறது...", closeBtn:"மூடு",
  sensorAdded:"✅ சென்சார் சேர்க்கப்பட்டது! இந்த Device Key-ஐ சேமிக்கவும்:",
  liveIot:"🔴 நேரடி IoT", mockData:"📊 மாதிரி தரவு",
  cropRecIot:"AI பயிர் பரிந்துரை (IoT தரவிலிருந்து)", confidenceMatch:"பொருத்தம்",
  connectIotTitle:"உங்கள் IoT சென்சாரை இணைக்கவும்",
  connectIotDesc:"தற்போது மாதிரி தரவு காட்டப்படுகிறது. சென்சார் சேர்த்து இணைந்தால் நேரடி தரவு தோன்றும்.",
  shareLearn:"பகிர் & கற்றுக்கொள்",
  profitHistoryLink:"💰 லாப வரலாறு", myPostsLink:"🌾 என் பதிவுகள்", diseaseHistLink:"🔬 நோய் வரலாறு",
  memberSince:"உறுப்பினர் தொடங்கியது", savingBtn:"சேமிக்கிறது...",
  saveError:"சேமிக்க முடியவில்லை. மீண்டும் முயலவும்.",
  titleDescRequired:"தலைப்பு மற்றும் விவரம் தேவை.",
  pleaseLoginFirst:"உள்நுழைந்த பிறகு முயலவும்.",
  postFailed:"பதிவு உருவாக்க முடியவில்லை. மீண்டும் முயலவும்.",
  maxFileSize:"JPG, PNG, WEBP — அதிகபட்சம் 5MB",
  removePhoto:"✕ படத்தை நீக்கு",
  posting:"⏳ பதிவிடுகிறது...",
},

/* Hindi */
hi: {
  home:"होम", dashboard:"डैशबोर्ड", farmMgmt:"फार्म प्रबंधन",
  sensors:"सेंसर मॉनिटर", crops:"फसल सलाह", irrigation:"सिंचाई",
  soil:"मिट्टी विश्लेषण", weather:"मौसम", reports:"रिपोर्ट",
  profile:"प्रोफ़ाइल", history:"फार्म इतिहास", logout:"लॉगआउट",
  welcomeBack:"वापस स्वागत है", signIn:"अपने AgroSmart अकाउंट में साइन इन करें",
  username:"यूज़रनेम", password:"पासवर्ड",
  farmer:"किसान", signInBtn:"साइन इन", newFarmer:"नया किसान?",
  createAcc:"मुफ्त अकाउंट बनाएं", orGuest:"या जारी रखें",
  guestMode:"अतिथि (केवल देखें)", fillAll:"कृपया सभी फ़ील्ड भरें।",
  createAccount:"अकाउंट बनाएं", registerSub:"अपना फार्म रजिस्टर करें",
  fullName:"पूरा नाम", mobile:"मोबाइल नंबर", village:"गांव / शहर",
  state:"राज्य", farmSize:"फार्म का आकार (एकड़)", primaryCrop:"मुख्य फसल",
  confirmPwd:"पासवर्ड की पुष्टि करें", alreadyHave:"पहले से अकाउंट है?",
  passwordsMustMatch:"पासवर्ड मेल नहीं खाते।", minChars:"कम से कम 6 अक्षर",
  farmSizePlaceholder:"जैसे 10",
  authStatFree:"मुफ्त", authStatForever:"हमेशा",
  authStatSetup:"5 मिनट", authStatSetupLabel:"सेटअप",
  authStat247:"24/7", authStatMonitoring:"निगरानी",
  heroTag:"🌱 आधुनिक भारत के लिए स्मार्ट खेती",
  heroTitle:"अपने फार्म की निगरानी करें", heroAccent:"कहीं से भी",
  heroSub:"रियल-टाइम मिट्टी, मौसम और फसल डेटा आपकी उंगलियों पर।",
  goToDash:"डैशबोर्ड पर जाएं", registerFree:"मुफ्त रजिस्टर करें",
  featuresTitle:"आपके फार्म को जो चाहिए सब कुछ",
  featuresSub:"किसानों के लिए बना एक पूर्ण कृषि निगरानी मंच।",
  aboutBadge:"प्रोजेक्ट के बारे में", aboutTitle:"भारत के किसानों के लिए बनाया",
  getStarted:"मुफ्त शुरू करें",
  ctaTitle:"अपने फार्म को बदलने के लिए तैयार?",
  ctaSub:"AgroSmart का उपयोग करने वाले हजारों किसानों से जुड़ें।",
  featuresLink:"विशेषताएं", aboutLink:"हमारे बारे में",
  farmersLabel:"किसान", uptimeLabel:"अपटाइम",
  waterSavedLabel:"पानी बचत", yieldBoostLabel:"उपज वृद्धि",
  featureRtSensors:"रियल-टाइम सेंसर",
  featureRtSensorsDesc:"मिट्टी की नमी, तापमान, pH और आर्द्रता की तुरंत निगरानी करें।",
  featureWeather:"मौसम बुद्धिमत्ता",
  featureWeatherDesc:"हाइपरलोकल मौसम पूर्वानुमान और सिंचाई अलर्ट पाएं।",
  featureIrrigation:"स्मार्ट सिंचाई",
  featureIrrigationDesc:"मिट्टी की नमी के आधार पर पानी देने का समय स्वचालित करें।",
  featureCrops:"फसल सिफारिश",
  featureCropsDesc:"मिट्टी के प्रोफाइल और जलवायु के अनुसार फसल सुझाव।",
  featureSoil:"मिट्टी स्वास्थ्य विश्लेषण",
  featureSoilDesc:"NPK स्तर, pH संतुलन और जैविक पदार्थों की निगरानी करें।",
  featureAnalytics:"विश्लेषण और रिपोर्ट",
  featureAnalyticsDesc:"विस्तृत रिपोर्ट और उपज भविष्यवाणी पाएं।",
  benefitNoTech:"कोई तकनीकी ज्ञान नहीं चाहिए",
  benefitMobile:"मोबाइल, टैबलेट, डेस्कटॉप — सभी पर काम करता है",
  benefitLang:"तमिल, हिंदी, अंग्रेजी समर्थन",
  benefitAlerts:"रियल-टाइम अलर्ट और सूचनाएं",
  benefitFree:"छोटे किसानों के लिए मुफ्त",
  benefitResearch:"कृषि अनुसंधान डेटा द्वारा समर्थित",
  aboutDesc:"AgroSmart भारतीय किसानों के लिए एक आधुनिक निगरानी मंच है।",
  footerTagline:"स्मार्ट कृषि निगरानी प्रणाली",
  footerCopyright:"© 2026 | Capstone Project | React PWA",
  smartAgriPlatform:"स्मार्ट कृषि मंच",
  liveDashboard:"लाइव डैशबोर्ड",
  goodMorning:"सुप्रभात", goodAfternoon:"नमस्ते", goodEvening:"शुभ संध्या",
  allSensorsActive:"आज का फार्म अवलोकन। सभी सेंसर सक्रिय हैं।",
  temperature:"तापमान", humidity:"आर्द्रता", soilMoisture:"मिट्टी की नमी",
  phLevel:"अम्लता स्तर", weeklyTrends:"साप्ताहिक सेंसर ट्रेंड",
  recentActivity:"हाल की गतिविधियां", quickAccess:"त्वरित पहुंच",
  optimalRange:"फसलों के लिए उचित सीमा", goodMoisture:"हवा में अच्छी नमी",
  wellIrrigated:"अच्छी तरह सींचा हुआ", neutralIdeal:"तटस्थ — आदर्श",
  alertLowBatteryTitle:"कम बैटरी — सेंसर अलर्ट",
  alertLowBatteryMsg:"नमी सेंसर (खेत द) 23% बैटरी पर है। डेटा हानि से बचने के लिए जल्द बदलें।",
  alertRainTitle:"बारिश का पूर्वानुमान — सिंचाई सलाह",
  alertRainMsg:"बुधवार को भारी बारिश की उम्मीद है। खेत स की सिंचाई रोकने पर विचार करें।",
  actIrrigation:"खेत अ में सिंचाई शुरू हुई",
  actLowBattery:"नमी सेंसर (खेत द) की बैटरी कम है",
  actHarvest:"खेत ब (चावल) की कटाई निर्धारित है",
  actPhReading:"नई अम्लता रीडिंग: 6.8 (सर्वोत्तम)",
  actRainForecast:"अगले 3 दिनों के लिए बारिश का पूर्वानुमान",
  actFertilizer:"गेहूं के खेत में NPK उर्वरक डाला गया",
  farmMgmtTitle:"फार्म प्रबंधन", farmMgmtSub:"अपने फार्म विवरण प्रबंधित करें",
  farmDetails:"फार्म विवरण", farmName:"फार्म का नाम", owner:"मालिक",
  location:"स्थान", totalArea:"कुल क्षेत्र", established:"स्थापित",
  soilTypeLabel:"मिट्टी का प्रकार", waterSource:"जल स्रोत", activeCrops:"सक्रिय फसलें",
  totalFields:"कुल खेत", irrigated:"सिंचित", healthyFields:"स्वस्थ खेत",
  needAttention:"ध्यान चाहिए", cropCalendar:"फसल कैलेंडर", fieldOverview:"खेत अवलोकन",
  health:"स्वास्थ्य", noIrrigation:"सिंचाई नहीं",
  farmLocation:"कोयम्बटूर, तमिलनाडु",
  borewellLabel:"बोरवेल", canalLabel:"नहर",
  fieldA:"खेत अ", fieldB:"खेत ब", fieldC:"खेत स", fieldD:"खेत द",
  allFields:"सभी खेत",
  cropRice:"चावल", cropWheat:"गेहूं", cropSugarcane:"गन्ना", cropCotton:"कपास",
  cropMaize:"मक्का", cropSoybean:"सोयाबीन", cropPulses:"दलहन", cropVegetables:"सब्जियां",
  areaAcre:"एकड़", seasonKharif:"खरीफ", seasonRabi:"रबी", seasonAnnual:"वार्षिक",
  irrDrip:"ड्रिप", irrSprinkler:"स्प्रिंकलर", irrFurrow:"नाली",
  mJun:"जून", mJul:"जुलाई", mAug:"अगस्त", mSep:"सितंबर", mOct:"अक्टूबर", mApr:"अप्रैल", mMay:"मई",
  calTask1:"बुवाई — चावल (खेत अ)", calTask2:"उर्वरक — गेहूं (खेत ब)",
  calTask3:"सिंचाई अनुसूची — खेत स", calTask4:"कीटनाशक — कपास (खेत द)",
  calTask5:"कटाई — चावल (खेत अ)",
  done:"हो गया", pending:"लंबित",
  sensorMonitor:"सेंसर निगरानी", sensorSub:"आपके खेतों में IoT सेंसर से लाइव डेटा",
  totalSensors:"कुल सेंसर", active:"सक्रिय", warning:"चेतावनी", offline:"ऑफलाइन",
  refreshData:"डेटा रिफ्रेश करें", refreshing:"रिफ्रेश हो रहा है...", allSensors:"सभी सेंसर",
  sensorDataLog:"सेंसर डेटा लॉग", sensorId:"सेंसर ID", name:"नाम", type:"प्रकार",
  currentValue:"वर्तमान मान", battery:"बैटरी", status:"स्थिति", lastUpdate:"अंतिम अपडेट",
  lowBattery:"कम बैटरी — जल्द बदलें",
  lastRefreshed:"अंतिम:", sensorStatusActive:"सक्रिय",
  sensorStatusWarning:"चेतावनी", sensorStatusInactive:"निष्क्रिय",
  sensorFieldA:"खेत अ - मिट्टी सेंसर", sensorFieldB:"खेत ब - तापमान सेंसर",
  sensorFieldC:"खेत स - pH सेंसर", sensorFieldD:"खेत द - नमी सेंसर",
  sensorGreenhouse:"ग्रीनहाउस - CO₂", sensorFieldE:"खेत इ - हवा सेंसर",
  su2min:"2 मिनट पहले", su1min:"1 मिनट पहले", su5min:"5 मिनट पहले",
  su3min:"3 मिनट पहले", su4min:"4 मिनट पहले", su2hrs:"2 घंटे पहले",
  cropAdvice:"फसल सिफारिशें", cropSub:"आपकी मिट्टी और जलवायु डेटा के आधार पर AI सुझाव",
  whyCrop:"यह फसल क्यों?", recFertilizer:"अनुशंसित उर्वरक (किग्रा/हेक्टेयर)",
  duration:"अवधि", waterNeed:"पानी की जरूरत", expectedYield:"अपेक्षित उपज",
  season:"मौसम", soilSummary:"मिट्टी विश्लेषण सारांश",
  overallScore:"कुल मिट्टी स्कोर", match:"मिलान",
  overallScoreNote:"आपकी मिट्टी खेती के लिए अच्छी स्थिति में है।",
  downloadSoilReport:"मिट्टी रिपोर्ट डाउनलोड करें",
  neutral:"तटस्थ — सर्वोत्तम", adequate:"पर्याप्त", slightlyHigh:"थोड़ा अधिक",
  good:"अच्छा", optimalRng:"उचित सीमा",
  dur120_150:"120-150 दिन", dur10_12m:"10-12 महीने", dur180_200:"180-200 दिन",
  waterHigh:"अधिक", waterMedium:"मध्यम",
  reasonRice:"सही मिट्टी pH (6.8), अधिक नमी (74%), तापमान (30-34°C) चावल के लिए आदर्श है।",
  reasonSugarcane:"पर्याप्त पोटेशियम वाली मिट्टी और गर्म जलवायु गन्ने की वृद्धि में मदद करती है।",
  reasonCotton:"मध्यम नाइट्रोजन और पर्याप्त धूप वाली लाल दोमट मिट्टी कपास के लिए उपयुक्त है।",
  yield45:"4.5 टन/एकड़", yield35:"35 टन/एकड़", yield18:"1.8 टन/एकड़",
  stageFlowering:"फूल आना", stageGermination:"अंकुरण",
  stageMaturation:"परिपक्वता", stageBollFormation:"टिंडे बनना",
  soilScore:"82/100",
  irrigationMgmt:"सिंचाई प्रबंधन", irrigationSub:"रियल टाइम में सिंचाई प्रणाली को नियंत्रित करें",
  waterToday:"आज पानी का उपयोग", thisWeek:"इस सप्ताह", efficiency:"दक्षता",
  nextScheduled:"अगला निर्धारित", motorControl:"मोटर नियंत्रण",
  mainPumpMotor:"मुख्य पंप मोटर", running:"चल रहा है", stopped:"बंद है",
  pumpOffline:"पंप ऑफलाइन है", startMotor:"मोटर शुरू करें", stopMotor:"मोटर बंद करें",
  fieldStatus:"खेत की स्थिति", irrigAlerts:"सिंचाई अलर्ट",
  startTime:"शुरुआत का समय", endTime:"समाप्ति का समय", schedule:"अनुसूची",
  waterReq:"पानी की आवश्यकता", scheduleIrrigation:"सिंचाई शेड्यूल करें",
  flow:"प्रवाह", dripIrrigation:"ड्रिप सिंचाई",
  motorRuntime:"मोटर रनटाइम", powerConsumption:"बिजली की खपत",
  motorRuntimeVal:"4 घंटे 20 मिनट", powerConsumptionVal:"2.4 किलोवाट घंटा",
  fieldStatus_irrigating:"सिंचाई हो रही है", fieldStatus_scheduled:"निर्धारित",
  fieldStatus_completed:"पूर्ण", fieldStatus_off:"बंद",
  tomorrowAM:"कल सुबह 6 बजे",
  irrDur1:"2 घंटे शेष", irrDur2:"कल सुबह 6 बजे", irrDur3:"सुबह 10 बजे पूरी हुई",
  irrFlow:"45 लि/मिनट",
  irrAlert1:"खेत द की मिट्टी नमी बहुत कम (42%). तुरंत सिंचाई की सलाह है।",
  irrAlert2:"2 दिन में बारिश की उम्मीद। खेत स की सिंचाई कम करने पर विचार करें।",
  irrAlert3:"खेत अ की सिंचाई दक्षता 91% — उत्तम प्रदर्शन।",
  swrSandyLoam:"जल्दी निकासी — छोटे अंतराल पर बार-बार सिंचाई करें।",
  swrClayLoam:"पानी अच्छी तरह रोकती है — अधिक सिंचाई से बचें।",
  swrSiltLoam:"संतुलित निकासी — सामान्य अनुसूची काम करती है।",
  swrRedLoam:"मध्यम निकासी — नमी पर नज़र रखें।",
  swrBlackCotton:"पानी बहुत रोकती है — सिंचाई कम करें।",
  swrUnit:"लि/एकड़/घंटा",
  soilAnalysis:"मिट्टी विश्लेषण", soilSub:"अपने खेतों में मिट्टी स्वास्थ्य की निगरानी करें",
  nitrogen:"नाइट्रोजन (N)", phosphorus:"फॉस्फोरस (P)", potassium:"पोटेशियम (K)",
  phLevelLabel:"अम्लता स्तर", organicMatter:"जैविक पदार्थ",
  soilTemp:"तापमान", moisture:"नमी", ideal:"आदर्श",
  phSimulator:"अम्लता स्तर सिम्युलेटर", soilNutrient:"मिट्टी पोषण प्रोफ़ाइल",
  soilType:"मिट्टी का प्रकार", waterNeeded:"आवश्यक पानी", waterSchedule:"सिंचाई अनुसूची",
  bestCrops:"सर्वोत्तम फसलें", drainage:"जल निकासी",
  veryAcidic:"बहुत अम्लीय", slightlyAcidic:"थोड़ा अम्लीय",
  neutralIdealPh:"तटस्थ — आदर्श", slightlyAlkaline:"थोड़ा क्षारीय", veryAlkaline:"बहुत क्षारीय",
  addLimeTip:"अम्लता बढ़ाने के लिए चूना डालें", teaBerryTip:"चाय, जामुन के लिए उपयुक्त",
  optimalCropTip:"अधिकांश फसलों के लिए सर्वोत्तम", addSulfurTip:"अम्लता कम करने के लिए सल्फर डालें",
  poorNutrientTip:"पोषक तत्व उपलब्ध नहीं",
  lowOrganicTitle:"खेत द में कम जैविक पदार्थ",
  lowOrganicMsg:"जैविक पदार्थ 1.8% — आदर्श से कम। अगले सीजन से पहले खाद डालें।",
  soilDrainage:"जल निकासी", bestCropsLabel:"सर्वोत्तम फसलें",
  currentSoilLabel:"वर्तमान मिट्टी", idealLabel:"आदर्श",
  requiredLabel:"आवश्यक", basedOnLabel:"के आधार पर",
  soilSandyLoam:"बलुई दोमट", soilClayLoam:"चिकनी दोमट", soilSiltLoam:"गाद दोमट",
  soilRedLoam:"लाल दोमट", soilBlackCotton:"काली कपास मिट्टी",
  scSandyLoam:"चावल, मूंगफली, सब्जियां", scClayLoam:"कपास, गन्ना, सोयाबीन",
  scSiltLoam:"गेहूं, मक्का, सूरजमुखी", scRedLoam:"कपास, मूंगफली, दलहन",
  scBlackCotton:"कपास, ज्वार, चना",
  spSandyLoam:"जल्दी निकासी — बार-बार सिंचाई करें। पोषक तत्व कम; खाद डालें।",
  spClayLoam:"पानी और पोषक तत्व अच्छी तरह रोकती है। जलभराव की संभावना — नालियां बनाएं।",
  spSiltLoam:"संतुलित निकासी। सामान्य सिंचाई से अधिकांश फसलों के लिए उत्तम।",
  spRedLoam:"अच्छी आयरन सामग्री। मध्यम पानी की जरूरत। pH नकदी फसलों के लिए आदर्श।",
  spBlackCotton:"बहुत अधिक पानी रोकती है। सिंचाई आवृत्ति काफी कम करें।",
  drainFast:"तेज़", drainSlow:"धीमी", drainModerate:"मध्यम", drainVerySlow:"बहुत धीमी",
  weatherOverview:"मौसम अवलोकन", weatherSub:"आपके फार्म के लिए हाइपरलोकल पूर्वानुमान",
  dayForecast:"7-दिन का पूर्वानुमान", farmImpact:"फार्म प्रभाव विश्लेषण",
  recommendations:"सिफारिशें", farmNews:"फार्म समाचार",
  partlyCloudy:"आंशिक बादल", humidity_lbl:"आर्द्रता", wind:"हवा",
  rainfall:"वर्षा", uvIndex:"UV सूचकांक", visibility:"दृश्यता", pressure:"दबाव",
  today:"आज", tomorrow:"कल",
  riceImpact:"लाभकारी — बारिश से सिंचाई की जरूरत कम होगी",
  wheatImpact:"सावधान — अधिक नमी से फंगल समस्या हो सकती है",
  sugarcaneImpact:"उत्तम — गर्म मौसम विकास में मदद करता है",
  cottonImpact:"निगरानी करें — भारी बारिश से नुकसान हो सकता है",
  tip1:"खेत अ और स के लिए सिंचाई रोकें — 2 दिनों की बारिश का पूर्वानुमान",
  tip2:"बुधवार की बारिश से पहले गेहूं पर फफूंदनाशक लगाएं",
  tip3:"खेत द में कपास को गुरुवार की बारिश से पहले काटें",
  tip4:"जलभराव रोकने के लिए निचले खेतों में नालियां जांचें",
  weatherSunny:"धूप", weatherClearSky:"साफ़ आसमान", weatherUvHigh:"(उच्च)",
  impactRiceCrop:"चावल (खेत अ)", impactWheatCrop:"गेहूं (खेत ब)",
  impactSugarCrop:"गन्ना (खेत स)", impactCottonCrop:"कपास (खेत द)",
  weatherHumidity:"68%", weatherWindSpeed:"14 कि.मी/घंटा",
  weatherRainfall:"12 मि.मी", weatherUvValue:"6",
  weatherVisibility:"8 कि.मी", weatherPressure:"1012 हेक्टोपास्कल", weatherTemp:"33°से",
  reportsAnalytics:"रिपोर्ट और विश्लेषण", reportsSub:"व्यापक अंतर्दृष्टि और प्रदर्शन डेटा",
  totalWater:"कुल पानी का उपयोग", avgSoil:"औसत मिट्टी स्वास्थ्य", cropYield:"फसल उत्पादन",
  activeAlerts:"सक्रिय अलर्ट", monthSummary:"मासिक सारांश",
  exportPDF:"पूरी रिपोर्ट निर्यात (PDF)", downloadCSV:"CSV डाउनलोड",
  month:"महीना", water:"पानी", temp:"तापमान", yield:"उपज",
  rainfallVsTemp:"वर्षा vs तापमान (वार्षिक)",
  monthlyCropYield:"मासिक फसल उत्पादन", waterSourceDist:"जल स्रोत वितरण",
  soilCol:"मिट्टी", rainfallMm:"वर्षा (मिमी)", avgTempC:"औसत तापमान (°C)", cropYieldPct:"फसल उत्पादन (%)",
  dripIrrigationLabel:"ड्रिप सिंचाई", rainwaterLabel:"वर्षा जल",
  rptPdfTitle:"AgroSmart फार्म रिपोर्ट", rptGenerated:"बनाया गया:",
  rptPdfFooter:"AgroSmart - स्मार्ट कृषि निगरानी प्रणाली द्वारा बनाया गया",
  rptPdfFilename:"AgroSmart_Report.txt", rptCsvFilename:"AgroSmart_Summary.csv",
  rptTotalWater:"कुल पानी का उपयोग", rptWaterVal:"28,450 लि",
  rptAvgSoil:"औसत मिट्टी स्वास्थ्य", rptSoilVal:"80%",
  rptCropYield:"फसल उत्पादन", rptYieldVal:"4.2 टन/एकड़", rptActiveAlerts:"सक्रिय अलर्ट",
  reportWaterUnit:"लि", reportTempUnit:"°से", reportYieldUnit:"टन/एकड़",
  unitKmh:"कि.मी/घंटा", unitMm:"मि.मी", unitC:"°से",
  unitL:"लि", unitKg:"किग्रा", unitMg:"मि.ग्रा", unitG:"ग्राम",
  unitKgHa:"किग्रा/हे.", unitMgKg:"मि.ग्रा/किग्रा", unitPpm:"पीपीएम",
  unitTAc:"टन/एकड़", unitKwh:"किलोवाट घंटा", unitHpa:"हेक्टोपास्कल",
  unitPercent:"%", unitAcre:"एकड़", unitLMin:"लि/मिनट", unitLAcHr:"लि/एकड़/घंटा",
  unitKg_s:"किग्रा", unitLitres:"लीटर", unitBags:"बोरे", unitGrams:"ग्राम", unitMl:"मिली",
  timeAM:"सुबह", timePM:"शाम",
  minAgo:"मिनट पहले", hrAgo:"घंटा पहले", hrsAgo:"घंटे पहले",
  farmHistory:"फार्म इतिहास", historySub:"सप्ताह दर सप्ताह सभी फार्म गतिविधियां ट्रैक करें",
  addActivity:"गतिविधि जोड़ें", activityType:"गतिविधि का प्रकार", quantity:"मात्रा",
  notes:"नोट्स", date:"तारीख", noHistory:"कोई इतिहास नहीं। गतिविधियां रिकॉर्ड करना शुरू करें।",
  field:"खेत", unit:"इकाई", aiSuggestion:"AI सुझाव", weekOf:"सप्ताह",
  fieldLabel:"खेत", all:"सभी", optionalNotes:"वैकल्पिक नोट्स",
  aiSuggestionPrefix:"AI सुझाव:",
  lastUsedMsg:"अंतिम उपयोग", considerSimilar:"इस सप्ताह समान मात्रा पर विचार करें।",
  histPlaceholder:"जैसे 25",
  act_urea:"यूरिया प्रयोग", act_pesticide:"कीटनाशक छिड़काव",
  act_npk:"उर्वरक (NPK)", act_dap:"DAP प्रयोग",
  act_potash:"पोटाश प्रयोग", act_organic:"जैविक खाद",
  act_irrigation:"सिंचाई", act_soilTest:"मिट्टी परीक्षण",
  act_harvest:"कटाई", act_sowing:"बुवाई / रोपाई",
  act_weeding:"निराई", act_fungicide:"फफूंदनाशक छिड़काव", act_other:"अन्य",
  myProfile:"मेरी प्रोफ़ाइल", editProfile:"प्रोफ़ाइल संपादित करें", saveProfile:"प्रोफ़ाइल सहेजें",
  deleteAccount:"अकाउंट हटाएं", confirmDelete:"क्या आप अपना अकाउंट हटाना चाहते हैं?",
  profileUpdated:"प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!", settings:"सेटिंग्स",
  dangerZone:"खतरा क्षेत्र", dangerNote:"अकाउंट हटाने से सभी डेटा स्थायी रूप से हट जाएगा।",
  settingsTitle:"सेटिंग्स", darkMode:"डार्क मोड", lightMode:"लाइट मोड",
  toggleTheme:"ऐप थीम बदलें", languageLabel:"भाषा",
  languageSub:"अपनी पसंदीदा भाषा चुनें",
  guestBrowsingMsg:"आप गेस्ट मोड में ब्राउज़ कर रहे हैं। डेटा सहेजने के लिए रजिस्टर करें।",
  yesDelete:"हाँ, हटाएं",
  notifications:"सूचनाएं", markAllRead:"सभी पढ़ा हुआ मार्क करें", noNotifications:"कोई नई सूचना नहीं",
  save:"सहेजें", cancel:"रद्द करें", edit:"संपादित करें", delete:"हटाएं", update:"अपडेट करें",
  search:"खोज", filter:"फ़िल्टर", export:"निर्यात", download:"डाउनलोड",
  selectState:"राज्य चुनें", selectCrop:"फसल चुनें", liveMode:"लाइव",
  farmSizePlaceholder:"जैसे 10",
  fertilizerRec:"उर्वरक सिफारिश",
  fertilizerSub:"फसल प्रकार और मिट्टी डेटा के आधार पर AI उर्वरक सुझाव",
  selectCropLabel:"फसल चुनें", recommendationLabel:"सिफारिश",
  pleaseSelectCrop:"सिफारिश देखने के लिए फसल चुनें",
  npkFertilizer:"NPK उर्वरक", ureaFertilizer:"यूरिया",
  dapFertilizer:"DAP", potashFertilizer:"पोटाश",
  fertilizerDetails:"उर्वरक विवरण", applicationRate:"उपयोग दर",
  applicationTime:"उपयोग का समय", benefits:"लाभ",
  precautions:"सावधानियां", mixingInstructions:"मिश्रण निर्देश",
  fertRateRice:"90-60-40 कि/हे.", fertTimeRice:"बेसल + कल्ले निकलते समय",
  fertBenRice:"कल्ले और दाने भरने में सुधार",
  fertPrecRice:"नाइट्रोजन बांटकर डालें", fertMixRice:"रोपाई से पहले छिड़कें",
  fertRateWheat:"60-30-30 कि/हे.", fertTimeWheat:"बुवाई + 21 दिन",
  fertBenWheat:"मजबूत जड़ विकास",
  fertPrecWheat:"DAP के बाद जलभराव से बचें", fertMixWheat:"सूखी मिट्टी में मिलाएं",
  fertRateCotton:"60-30-60 कि/हे.", fertTimeCotton:"45 और 75 दिन",
  fertBenCotton:"टिंडे बनना, रेशे की गुणवत्ता",
  fertPrecCotton:"अधिक न डालें — पत्ती जल सकती है", fertMixCotton:"पानी में घोलें",
  fertRateSugarcane:"120-60-120 कि/हे.", fertTimeSugarcane:"रोपाई + रतून",
  fertBenSugarcane:"तेज वानस्पतिक विकास",
  fertPrecSugarcane:"3 बार में बांटकर डालें", fertMixSugarcane:"जड़ क्षेत्र के पास छिड़कें",
  adminPanel:"एडमिन पैनल", systemHealthy:"सिस्टम स्वस्थ है",
  uptimeMonth:"इस महीने अपटाइम", systemOpsMsg:"सिस्टम स्थिति: सभी सिस्टम चालू हैं।",
  registeredFarmers:"पंजीकृत किसान", goToFarmerDash:"किसान डैशबोर्ड पर जाएं",
  nameCol:"नाम", villageCol:"गांव", cropCol:"फसल", areaCol:"क्षेत्र", statusCol:"स्थिति",
  farmerActive:"सक्रिय", farmerInactive:"निष्क्रिय",
  adminFarmer1Name:"राजेश कुमार", adminFarmer1Village:"पोल्लाची",
  adminFarmer2Name:"प्रिया देवी", adminFarmer2Village:"इरोड",
  adminFarmer3Name:"सुरेश बाबू", adminFarmer3Village:"सेलम",
  adminFarmer4Name:"कविता एम.", adminFarmer4Village:"मदुरई",
  newsNotFound:"लेख नहीं मिला", newsGoBack:"वापस जाएं", newsBack:"पीछे",
  newsTodayFarmNews:"आज की फार्म खबरें",
  newsReadTime3:"3 मिनट पढ़ाई", newsReadTime4:"4 मिनट पढ़ाई", newsReadTime5:"5 मिनट पढ़ाई",
  newsAlertTitle:"सेंसर बैटरी जीवन और रखरखाव",
  newsAlertCategory:"सेंसर रखरखाव",
  newsAlertB1:"IoT मिट्टी सेंसर एक चार्ज पर 6-12 महीने चलते हैं। कम बैटरी गलत रीडिंग दे सकती है।",
  newsAlertB2:"सर्वोत्तम प्रथाएं:", newsAlertB3:"• साप्ताहिक बैटरी स्तर जांचें",
  newsAlertB4:"• 25% से नीचे जाने पर बदलें", newsAlertB5:"• मासिक साफ करें",
  newsAlertB6:"• सीधी धूप में न रखें", newsAlertB7:"• ठंडी जगह में रखें",
  newsAlertB8:"आर्द्रता सेंसर बैटरी खराब होने के प्रति विशेष रूप से संवेदनशील हैं।",
  newsWeatherTitle:"भारी बारिश के लिए अपना खेत कैसे तैयार करें",
  newsWeatherCategory:"मौसम सलाह",
  newsWeatherB1:"भारी बारिश से जलभराव और फसल क्षति हो सकती है।",
  newsWeatherB2:"नाली तैयारी:", newsWeatherB3:"• बारिश से पहले सभी नाली चैनल साफ करें",
  newsWeatherB4:"• मेड़ सही हों", newsWeatherB5:"• नीचे के क्षेत्र में अस्थायी पंप लगाएं",
  newsWeatherB6:"फसल सुरक्षा:", newsWeatherB7:"• बारिश के 48 घंटे पहले उर्वरक न डालें",
  newsWeatherB8:"• ऊंची फसलों को सहारा दें", newsWeatherB9:"• पकी फसलें तुरंत काटें",
  newsWeatherB10:"सिंचाई:", newsWeatherB11:"• बारिश से 24-48 घंटे पहले सिंचाई बंद करें",
  newsWeatherB12:"• बारिश के बाद पंप जांचें",
  newsWeatherB13:"बारिश के बाद:", newsWeatherB14:"• भारी बारिश के बाद मिट्टी pH जांचें",
  newsWeatherB15:"• आर्द्र स्थितियों में फफूंद रोगों की निगरानी करें",
  newsCropTitle:"चावल की कटाई: तैयारी के संकेत", newsCropCategory:"फसल प्रबंधन",
  newsCropB1:"सही समय पर कटाई से दाने की गुणवत्ता और उपज अधिकतम होती है।",
  newsCropB2:"चावल तैयार होने के संकेत:", newsCropB3:"• 80-85% दाने सुनहरे पीले",
  newsCropB4:"• दाने की नमी 20-25%", newsCropB5:"• बाली नीचे झुकती है",
  newsCropB6:"• पत्तियां पीली/भूरी हो गई हों",
  newsCropB7:"कटाई का समय:", newsCropB8:"• 50% बाली निकलने के 28-32 दिन बाद काटें",
  newsCropB9:"• सुबह की कटाई बेहतर", newsCropB10:"• गीली स्थितियों में कटाई से बचें",
  newsCropB11:"कटाई के बाद:", newsCropB12:"• 14% नमी तक सुखाएं",
  newsCropB13:"• सूखे बोरों में भंडारण करें", newsCropB14:"• नीम पत्ते से कीट रोकें",
  newsSoilTitle:"अधिकतम उपज के लिए सही मिट्टी pH", newsSoilCategory:"मिट्टी स्वास्थ्य",
  newsSoilB1:"मिट्टी pH पोषक तत्वों की उपलब्धता नियंत्रित करती है।",
  newsSoilB2:"pH और पोषक तत्व:", newsSoilB3:"• pH 6.0-7.0: चावल, गेहूं, मक्का, कपास के लिए सर्वोत्तम",
  newsSoilB4:"• pH 5.5 से नीचे: लौह विषाक्तता", newsSoilB5:"• pH 7.5 से ऊपर: फास्फोरस अनुपलब्ध",
  newsSoilB6:"अम्लीय मिट्टी सुधार:", newsSoilB7:"• 1-2 टन/एकड़ चूना डालें",
  newsSoilB8:"• डोलोमाइट चूना उपयोग करें", newsSoilB9:"• 2-4 सप्ताह दें",
  newsSoilB10:"क्षारीय मिट्टी सुधार:", newsSoilB11:"• 200-400 किग्रा/एकड़ सल्फर डालें",
  newsSoilB12:"• अम्लीय उर्वरक उपयोग करें", newsSoilB13:"• सोडिक मिट्टी में जिप्सम",
  newsSoilB14:"साल में कम से कम दो बार मिट्टी pH जांचें।",
  newsIrrigTitle:"ड्रिप सिंचाई दक्षता", newsIrrigCategory:"सिंचाई प्रबंधन",
  newsIrrigB1:"ड्रिप सिंचाई 30-50% पानी बचा सकती है और उपज 20-30% बढ़ा सकती है।",
  newsIrrigB2:"सिस्टम रखरखाव:", newsIrrigB3:"• साप्ताहिक ड्रिप लाइन फ्लश करें",
  newsIrrigB4:"• मासिक एमिटर रुकावटें जांचें", newsIrrigB5:"• पंप पर फिल्टर लगाएं",
  newsIrrigB6:"समय-सारणी:", newsIrrigB7:"• सुबह या शाम सिंचाई करें",
  newsIrrigB8:"• सेंसर से केवल जरूरत पर सिंचाई करें",
  newsIrrigB9:"• कटाई से 2 सप्ताह पहले सिंचाई कम करें",
  newsIrrigB10:"फर्टिगेशन:", newsIrrigB11:"• ड्रिप सिस्टम से फर्टिगेशन करें",
  newsIrrigB12:"• यूरिया और पोटेशियम नाइट्रेट अच्छी तरह घुलते हैं",
  newsIrrigB13:"• एक ही टैंक में कैल्शियम और फास्फेट न मिलाएं",
  newsIrrigB14:"स्वचालित पानी की जरूरत गणना के लिए मिट्टी के प्रकार के आधार पर अनुसूची सेट करें।",
  dailyNews1Title:"आज की मौसम आधारित फार्म सलाह", dailyNews1Category:"मौसम सलाह",
  dailyNews1B1:"आज की स्थितियां (32°C, आंशिक बादल) कीटनाशक छिड़काव के लिए आदर्श हैं।",
  dailyNews1B2:"मिट्टी की नमी 74% — आज सिंचाई की जरूरत नहीं।",
  dailyNews1B3:"UV सूचकांक 6 (उच्च) — सुरक्षात्मक कपड़े पहनें।",
  dailyNews2Title:"जून खेती कैलेंडर: इस सप्ताह क्या करें", dailyNews2Category:"मौसमी सुझाव",
  dailyNews2B1:"खरीफ मौसम शुरू। मिट्टी नमी 70-80% हो तो धान रोपाई आदर्श।",
  dailyNews2B2:"धान को दूसरी नाइट्रोजन उर्वरक खुराक दें।",
  dailyNews2B3:"तना बेधक की निगरानी करें। 5% से अधिक पर कीटनाशक छिड़कें।",
  dailyNews2B4:"मानसून में गन्ने के गिरने से बचाने के लिए मिट्टी चढ़ाई करें।",
  dailyNews3Title:"वर्तमान फसल मूल्य रुझान — जून 2026", dailyNews3Category:"बाजार अपडेट",
  dailyNews3B1:"धान: Rs.2,100-2,200/क्विंटल। कटाई के बाद 5-8% वृद्धि की उम्मीद।",
  dailyNews3B2:"कपास: Rs.6,800-7,000/क्विंटल। कपड़ा मिलों में मजबूत मांग।",
  dailyNews3B3:"गेहूं: Rs.2,300/क्विंटल MSP। बाजार मूल्य स्थिर।",
  dailyNews3B4:"बेहतर मूल्य खोज के लिए eNAM पोर्टल पर पंजीकरण करें।",
  notif1Title:"कम बैटरी सेंसर", notif1Body:"आर्द्रता सेंसर 23% पर है। जल्द बदलें।",
  notif2Title:"बारिश पूर्वानुमान", notif2Body:"बुधवार को भारी बारिश। सिंचाई रोकें।",
  notif3Title:"फसल कटाई तैयार", notif3Body:"खेत अ में चावल इस सप्ताह कटाई के लिए तैयार।",
  notif4Title:"pH स्तर उत्तम", notif4Body:"मिट्टी pH 6.8 — वर्तमान फसलों के लिए आदर्श।",
  notif5Title:"सिंचाई पूर्ण", notif5Body:"खेत स सिंचाई पूर्ण। 450 लि उपयोग।",
  /* community — Hindi */
  community:"किसान समुदाय", communitySub:"अपनी खेती की सफलता साझा करें और दूसरों से सीखें",
  createPost:"पोस्ट बनाएं", createPostSub:"अपना खेती का अनुभव समुदाय के साथ साझा करें",
  postTitle:"पोस्ट शीर्षक", postTitlePlaceholder:"जैसे इस साल मेरी सबसे अच्छी धान की फसल!",
  postDescPlaceholder:"फसल, उपयोग की गई तकनीक, क्या अच्छा रहा — विवरण दें...",
  addPhoto:"फोटो जोड़ें (वैकल्पिक)", clickToUpload:"खेत की फोटो अपलोड करें",
  publishPost:"पोस्ट प्रकाशित करें", noPosts:"अभी कोई पोस्ट नहीं। पहले साझा करें!",
  comments:"टिप्पणियाँ", writeComment:"टिप्पणी लिखें...", noComments:"अभी कोई टिप्पणी नहीं।",
  /* profit history — Hindi */
  profitHistory:"लाभ इतिहास", profitSub:"अपनी कमाई ट्रैक करें और सफलता साझा करें",
  totalInvestment:"कुल निवेश", totalRevenue:"कुल आय", netGain:"शुद्ध लाभ",
  cropName:"फसल का नाम", investment:"निवेश (₹)", revenue:"आय (₹)",
  noProfitHistory:"अभी कोई लाभ रिकॉर्ड नहीं। पहला रिकॉर्ड जोड़ें!",
  /* disease detection — Hindi */
  diseaseDetection:"रोग पहचान और खेत विश्लेषण",
  diseaseDetectionSub:"फसल या खेत की फोटो अपलोड करें और AI विश्लेषण पाएं",
  analysisHistory:"पहचान इतिहास",
  /* irrigation weather — Hindi */
  motorControl:"मोटर नियंत्रण", autoWeatherMode:"स्वचालित मौसम मोड",
  autoWeatherDesc:"बारिश के पूर्वानुमान के आधार पर मोटर ON/OFF",
  weatherForLand:"आपकी जमीन के लिए मौसम", setLocation:"स्थान सेट करें",
  motorRecommendation:"मोटर सिफारिश", rainExpected:"बारिश की उम्मीद है",
  noRainExpected:"बारिश नहीं — सिंचाई जरूरी",
  runAutoDecision:"अभी स्वचालित निर्णय लें",
  motorActivityLog:"मोटर गतिविधि लॉग",
  /* sensors — Hindi */
  addIotSensor:"IoT सेंसर जोड़ें", registerNewSensor:"नया IoT सेंसर रजिस्टर करें",
  sensorName:"सेंसर का नाम", sensorType:"प्रकार", fieldName:"खेत का नाम",
  sensorTypeMulti:"सभी", sensorTypeSoil:"मिट्टी नमी",
  sensorTypeTemp:"तापमान", sensorTypeHumidity:"आर्द्रता",
  sensorTypePh:"अम्लता", sensorTypeNpk:"एनपीके",
  addSensorBtn:"सेंसर जोड़ें", addingBtn:"जोड़ रहे हैं...", closeBtn:"बंद करें",
  sensorAdded:"✅ सेंसर जोड़ा गया! यह Device Key सहेजें:",
  liveIot:"🔴 लाइव IoT", mockData:"📊 नमूना डेटा",
  cropRecIot:"AI फसल सिफारिश (IoT डेटा से)", confidenceMatch:"मिलान",
  connectIotTitle:"अपना IoT सेंसर जोड़ें",
  connectIotDesc:"अभी नमूना डेटा दिख रहा है। सेंसर जोड़ने के बाद लाइव डेटा दिखेगा।",
  shareLearn:"साझा करें & सीखें",
  profitHistoryLink:"💰 लाभ इतिहास", myPostsLink:"🌾 मेरी पोस्ट", diseaseHistLink:"🔬 रोग इतिहास",
  memberSince:"सदस्य बने", savingBtn:"सहेज रहे हैं...",
  saveError:"सहेजा नहीं गया। पुनः प्रयास करें।",
  titleDescRequired:"शीर्षक और विवरण आवश्यक है।",
  pleaseLoginFirst:"पहले लॉगिन करें।",
  postFailed:"पोस्ट नहीं बन सका। पुनः प्रयास करें।",
  maxFileSize:"JPG, PNG, WEBP — अधिकतम 5MB",
  removePhoto:"✕ फोटो हटाएं",
  posting:"⏳ पोस्ट हो रहा है...",
},

};


const SEED_NOTIFS = [
  { id:1, type:"alert",   title:"Low Battery Sensor",  body:"Humidity Sensor at 23%. Replace soon.",             time:"10m ago", read:false, link:"/sensors"   },
  { id:2, type:"weather", title:"Rain Forecast",        body:"Heavy rain expected Wednesday. Pause irrigation.",  time:"1h ago",  read:false, link:"/weather"   },
  { id:3, type:"crop",    title:"Crop Harvest Ready",   body:"Rice in Field A is ready for harvest this week.",   time:"3h ago",  read:true,  link:"/crops"     },
  { id:4, type:"soil",    title:"pH Level Optimal",     body:"Soil pH at 6.8 — ideal for current crops.",         time:"5h ago",  read:true,  link:"/soil"      },
  { id:5, type:"irrig",   title:"Irrigation Complete",  body:"Field C irrigation completed. 450L used.",          time:"8h ago",  read:true,  link:"/irrigation"},
];

const getMotorState = () => {
  try { return JSON.parse(localStorage.getItem("motorState")) || { on:false, waterUsed:1240 }; }
  catch { return { on:false, waterUsed:1240 }; }
};

export function AppProvider({ children }) {
  const [lang,       setLangState] = useState(() => localStorage.getItem("agro_lang") || "en");
  const [darkMode,   setDarkMode]  = useState(() => localStorage.getItem("agro_dark") === "true");
  const [motorState, setMotorState] = useState(getMotorState);
  const [notifications, setNotifications] = useState(() => {
    try { return JSON.parse(localStorage.getItem("agro_notifs")) || SEED_NOTIFS; }
    catch { return SEED_NOTIFS; }
  });
  const [farmHistory, setFarmHistory] = useState(() => {
    try { return JSON.parse(localStorage.getItem("agro_history")) || []; }
    catch { return []; }
  });

  // Auth state — synced with localStorage
  const [user, setUserState] = useState(() => {
    try { return JSON.parse(localStorage.getItem("user")) || null; }
    catch { return null; }
  });

  // ═══════════════════════════════════════════════════════════
  //  CROSS-FEATURE SHARED STATE — connects the full flow:
  //  Farm → Weather → Soil → Crops → Irrigation → Disease → Community
  // ═══════════════════════════════════════════════════════════

  // Latest soil analysis result (set by Soil page after analysis)
  const [sharedSoilResult, setSharedSoilResult] = useState(() => {
    try { return JSON.parse(localStorage.getItem("agro_soil_result")) || null; }
    catch { return null; }
  });

  // Latest crop recommendations (set by Crops page)
  const [sharedCropRec, setSharedCropRec] = useState(() => {
    try { return JSON.parse(localStorage.getItem("agro_crop_rec")) || null; }
    catch { return null; }
  });

  // Latest sensor data (set by Dashboard/Sensors via WebSocket)
  const [sharedSensorData, setSharedSensorData] = useState(null);

  // Farm location set in Irrigation page
  const [sharedFarmLocation, setSharedFarmLocation] = useState(() => {
    try { return JSON.parse(localStorage.getItem("agro_farm_location")) || null; }
    catch { return null; }
  });

  // Weather result from irrigation page
  const [sharedWeather, setSharedWeather] = useState(null);

  // Latest disease detection result (set by Disease page)
  const [sharedDiseaseResult, setSharedDiseaseResult] = useState(null);

  // Flow completion tracker — which steps are done
  const [flowStatus, setFlowStatus] = useState(() => {
    try { return JSON.parse(localStorage.getItem("agro_flow_status")) || {
      farmDetails: false,
      weatherSet: false,
      soilDone: false,
      cropsDone: false,
      irrigationDone: false,
      diseaseDone: false,
      communityDone: false,
    }; }
    catch { return {
      farmDetails: false, weatherSet: false, soilDone: false,
      cropsDone: false, irrigationDone: false, diseaseDone: false, communityDone: false,
    }; }
  });

  // Persist cross-feature state
  useEffect(() => {
    if (sharedSoilResult) localStorage.setItem("agro_soil_result", JSON.stringify(sharedSoilResult));
  }, [sharedSoilResult]);

  useEffect(() => {
    if (sharedCropRec) localStorage.setItem("agro_crop_rec", JSON.stringify(sharedCropRec));
  }, [sharedCropRec]);

  useEffect(() => {
    if (sharedFarmLocation) localStorage.setItem("agro_farm_location", JSON.stringify(sharedFarmLocation));
  }, [sharedFarmLocation]);

  useEffect(() => {
    localStorage.setItem("agro_flow_status", JSON.stringify(flowStatus));
  }, [flowStatus]);

  // Mark a flow step complete
  const markFlowStep = useCallback((step) => {
    setFlowStatus(prev => ({ ...prev, [step]: true }));
  }, []);

  // Reset flow (e.g. new season)
  const resetFlow = useCallback(() => {
    setFlowStatus({
      farmDetails: false, weatherSet: false, soilDone: false,
      cropsDone: false, irrigationDone: false, diseaseDone: false, communityDone: false,
    });
    setSharedSoilResult(null);
    setSharedCropRec(null);
    setSharedDiseaseResult(null);
    localStorage.removeItem("agro_soil_result");
    localStorage.removeItem("agro_crop_rec");
    localStorage.removeItem("agro_flow_status");
  }, []);

  // Smart irrigation alert: soil moisture < 40 → suggest motor on
  const irrigationAlert = useMemo(() => {
    if (!sharedSensorData) return null;
    const moisture = parseFloat(sharedSensorData.soil_moisture);
    if (isNaN(moisture) || moisture >= 40) return null;
    return { type: "low_moisture", value: moisture };
  }, [sharedSensorData]);

  const setUser = useCallback((u) => {
    setUserState(u);
    if (u) {
      localStorage.setItem("user", JSON.stringify(u));
      // ✅ Restore user's preferred language from DB on login
      if (u.preferred_lang && ["en", "ta", "hi"].includes(u.preferred_lang)) {
        setLangState(u.preferred_lang);
        localStorage.setItem("agro_lang", u.preferred_lang);
      }
    }
    else { localStorage.removeItem("user"); localStorage.removeItem("token"); }
  }, []);

  const logout = useCallback(() => {
    setUserState(null);
    localStorage.removeItem("user");
    localStorage.removeItem("token");
    localStorage.removeItem("loggedIn");
  }, []);

  const setLang = (l) => {
    setLangState(l);
    localStorage.setItem("agro_lang", l);
    // ✅ Save preferred language to DB if user is logged in
    const token = localStorage.getItem("token");
    if (token) {
      fetch("http://localhost:5000/api/auth/set-lang", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify({ lang: l }),
      }).catch(() => {}); // non-blocking, silent fail
    }
  };

  const t = T[lang] || T.en;

  useEffect(() => {
    localStorage.setItem("agro_dark", String(darkMode));
    document.documentElement.setAttribute("data-theme", darkMode ? "dark" : "light");
  }, [darkMode]);

  useEffect(() => { localStorage.setItem("motorState",   JSON.stringify(motorState));   }, [motorState]);
  useEffect(() => { localStorage.setItem("agro_notifs",  JSON.stringify(notifications)); }, [notifications]);

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", darkMode ? "dark" : "light");
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const setMotor           = useCallback((on)  => { setMotorState(p => ({ ...p, on })); }, []);
  const addWater           = useCallback((amt) => { setMotorState(p => ({ ...p, waterUsed: p.waterUsed + amt })); }, []);
  const markNotifRead      = useCallback((id)  => { setNotifications(p => p.map(n => n.id === id ? { ...n, read:true } : n)); }, []);
  const markAllRead        = useCallback(()    => { setNotifications(p => p.map(n => ({ ...n, read:true }))); }, []);

  const unreadCount = notifications.filter(n => !n.read).length;

  return (
    <AppContext.Provider value={{
      lang, setLang, t,
      darkMode, setDarkMode,
      motorState, setMotor, addWater,
      notifications, markNotifRead, markAllRead, unreadCount,
      user, setUser, logout,
      // Cross-feature shared state
      sharedSoilResult, setSharedSoilResult,
      sharedCropRec, setSharedCropRec,
      sharedSensorData, setSharedSensorData,
      sharedFarmLocation, setSharedFarmLocation,
      sharedWeather, setSharedWeather,
      sharedDiseaseResult, setSharedDiseaseResult,
      flowStatus, markFlowStep, resetFlow,
      irrigationAlert,
    }}>
      {children}
    </AppContext.Provider>
  );
}
